import type {Locale} from "@/i18n/routing";

type Section = {title: string; text: string};
type LegalCopy = {privacy: string; deletion: string; updated: string; contact: string; home: string; privacyIntro: string; deletionIntro: string; sections: Section[]; steps: Section[]};

export const legalContent = {
  en: {
    privacy: "Privacy Policy", deletion: "Data deletion instructions", updated: "Updated 6 October 2026", contact: "Contact LumaClean", home: "Back to the website",
    privacyIntro: "This policy explains how LumaClean handles information when you visit our website, contact us or arrange cleaning in Belgrade. It also covers our website chat and WhatsApp channel.",
    deletionIntro: "You can ask LumaClean to delete information associated with your enquiries, conversations and cleaning orders. You do not need a website account to make a request.",
    sections: [
      {title: "Information we receive", text: "We receive the messages you send, your channel identifier or phone number, and any name or contact details you provide. When arranging cleaning, this may include the cleaning address, property details, requested services, dates, estimates and order information. We retain conversation history and images or files you attach. Please share only information needed for your enquiry and avoid sending identity documents, payment credentials or sensitive images."},
      {title: "Why we use it", text: "We use this information to answer enquiries, estimate prices, arrange cleaning, manage orders and provide support. Technical information such as message identifiers, delivery receipts, timestamps, session information and security logs helps us deliver messages, prevent duplicates and protect the service."},
      {title: "WhatsApp and Meta", text: "Our WhatsApp channel uses the WhatsApp Business Platform provided by Meta. Messages and delivery events are processed through Meta and our service. Meta also processes information under its own policies. Deleting a copy from LumaClean does not delete your WhatsApp account or copies held by you or Meta."},
      {title: "Automated assistance and service providers", text: "Some messages and attached images may be processed by an automated AI assistant to understand your request, prepare a reply or assist with booking. You can ask to speak to a person. Information needed for these functions is processed by our hosting, database, file storage, messaging and AI service providers, including Vercel, Neon, Meta, PoYo and OpenRouter. We share the information needed to operate the service, rather than publish your conversations. Providers may process information outside Serbia under their own terms and privacy policies."},
      {title: "Website analytics", text: "Optional Google Analytics loads only after you allow analytics through the website privacy controls. It receives page and interaction information and technical device data, and may use cookies. We do not send enquiry text, names or phone numbers to analytics. You can change your analytics choice using Privacy settings on the website."},
      {title: "Storage and security", text: "We keep information needed for enquiries, active orders, support and necessary operational or legal records. Retention depends on the purpose and your deletion request; we do not promise a single fixed period for every record. Administrative access is restricted, attachments use private storage, and credentials are kept on the server. No system can guarantee absolute security. Backup copies may remain until they are replaced or expire in the normal backup cycle."},
      {title: "Your requests", text: "You may contact us to ask about the information we hold, request corrections or request deletion. We may need to verify that the request concerns your own data. Some records may need to be retained for an active order, a dispute or applicable obligations; we will explain any such limitation. Use the deletion instructions below or contact us through the channels listed here."},
    ],
    steps: [
      {title: "1. Contact us", text: "Send a message to LumaClean through the WhatsApp link below and say that you want your data deleted. If you cannot access that channel, call the published contact number to arrange another way to make the request."},
      {title: "2. Identify the data", text: "Tell us the phone number or channel used to contact LumaClean and what you want deleted, such as conversation history, attachments or an enquiry. If available, include an order reference or approximate conversation date. Do not send passwords, access tokens or identity documents in your initial request."},
      {title: "3. Verification and review", text: "An administrator checks the request and may ask you to confirm control of the original contact channel. We review which information can be deleted and whether any active order, dispute or applicable record-keeping requirement prevents immediate deletion of particular records."},
      {title: "4. Completion", text: "We delete eligible data from our active records and arrange deletion with relevant service providers where applicable. We will confirm completion or explain what must be retained and why. Backup copies are not necessarily removed immediately; they expire or are replaced according to the backup cycle. This request does not delete your WhatsApp account or copies controlled by Meta or other participants."},
    ],
  },
  ru: {
    privacy: "Политика конфиденциальности", deletion: "Удаление данных", updated: "Обновлено 6 октября 2026", contact: "Связаться с LumaClean", home: "Вернуться на сайт",
    privacyIntro: "Здесь описано, как LumaClean обрабатывает информацию при посещении сайта, переписке и заказе уборки в Белграде. Политика распространяется на чат сайта и WhatsApp.",
    deletionIntro: "Вы можете запросить удаление данных, связанных с обращениями, перепиской и заказами уборки. Аккаунт на сайте для этого не нужен.",
    sections: [
      {title: "Какие данные мы получаем", text: "Мы получаем ваши сообщения, идентификатор канала или номер телефона, а также имя и контакты, если вы их предоставляете. При заказе это могут быть адрес уборки, сведения о помещении, услуги, даты, расчёт цены и данные заказа. Мы сохраняем историю переписки и приложенные изображения или файлы. Передавайте только необходимые сведения; не отправляйте документы, платёжные реквизиты и чувствительные изображения."},
      {title: "Для чего используются данные", text: "Для ответов на вопросы, расчёта цены, записи на уборку, обслуживания заказов и поддержки. Идентификаторы сообщений, статусы доставки, время событий, данные сессии и журналы безопасности нужны для работы переписки, предотвращения дублей и защиты сервиса."},
      {title: "WhatsApp и Meta", text: "Канал WhatsApp использует WhatsApp Business Platform компании Meta. Сообщения и события доставки проходят через Meta и наш сервис. Meta также обрабатывает данные по собственным правилам. Удаление копии из LumaClean не удаляет ваш аккаунт WhatsApp или копии у вас и Meta."},
      {title: "ИИ и поставщики сервисов", text: "Некоторые сообщения и изображения может обрабатывать автоматизированный ИИ-помощник для понимания запроса, подготовки ответа и помощи с записью. Можно попросить подключить человека. Необходимые данные обрабатывают поставщики хостинга, базы данных, хранения файлов, переписки и ИИ, включая Vercel, Neon, Meta, PoYo и OpenRouter. Мы передаём сведения для работы сервиса, а не публикуем переписку. Провайдеры могут обрабатывать данные за пределами Сербии по своим условиям и политикам."},
      {title: "Аналитика сайта", text: "Необязательная Google Analytics загружается только после разрешения в настройках конфиденциальности сайта. Она получает сведения о страницах, действиях и технических данных устройства и может использовать cookies. Текст обращений, имена и телефоны в аналитику не отправляются. Выбор можно изменить через настройки конфиденциальности на сайте."},
      {title: "Хранение и безопасность", text: "Мы храним данные, необходимые для обращений, текущих заказов, поддержки и обязательных операционных или правовых записей. Срок зависит от цели и запроса на удаление; единого фиксированного срока для всех записей нет. Доступ администратора ограничен, вложения хранятся приватно, секреты — на сервере. Абсолютную безопасность не может гарантировать ни одна система. Резервные копии могут сохраняться до их замены или истечения срока обычного цикла резервирования."},
      {title: "Ваши запросы", text: "Свяжитесь с нами, чтобы узнать о сохранённых данных, исправить их или запросить удаление. Может потребоваться подтверждение, что данные принадлежат вам. Часть записей может быть необходима для текущего заказа, спора или обязательных требований; мы объясним ограничения. Используйте инструкцию удаления ниже или указанные контакты."},
    ],
    steps: [
      {title: "1. Свяжитесь с нами", text: "Напишите LumaClean в WhatsApp по ссылке ниже и укажите, что хотите удалить свои данные. Если этот канал недоступен, позвоните по публичному контактному номеру, чтобы согласовать другой способ обращения."},
      {title: "2. Уточните данные", text: "Укажите номер телефона или канал общения с LumaClean и что нужно удалить: переписку, вложения или обращение. При наличии добавьте номер заказа или примерную дату разговора. Не отправляйте пароли, токены и документы в первоначальном запросе."},
      {title: "3. Проверка запроса", text: "Администратор проверяет запрос и при необходимости просит подтвердить доступ к исходному каналу. Мы определяем, какие сведения можно удалить и нужно ли сохранить отдельные записи для текущего заказа, спора или обязательного учёта."},
      {title: "4. Завершение", text: "Мы удаляем доступные для удаления данные из действующих записей и при необходимости обращаемся к соответствующим провайдерам. Сообщим о результате или объясним, что сохраняется и почему. Резервные копии не обязательно удаляются мгновенно: они заменяются или истекают в рамках цикла резервирования. Запрос не удаляет аккаунт WhatsApp и копии, которыми управляют Meta или другие участники переписки."},
    ],
  },
  sr: {
    privacy: "Politika privatnosti", deletion: "Uputstvo za brisanje podataka", updated: "Ažurirano 6. oktobra 2026.", contact: "Kontaktirajte LumaClean", home: "Nazad na sajt",
    privacyIntro: "Ova politika opisuje kako LumaClean obrađuje informacije kada posetite sajt, kontaktirate nas ili dogovarate čišćenje u Beogradu. Obuhvata čet na sajtu i WhatsApp kanal.",
    deletionIntro: "Možete zatražiti brisanje podataka povezanih sa upitima, razgovorima i narudžbinama čišćenja. Nalog na sajtu nije potreban.",
    sections: [
      {title: "Podaci koje primamo", text: "Primamo poruke koje šaljete, identifikator kanala ili broj telefona i ime i kontakt podatke koje navedete. Za čišćenje to mogu biti adresa, podaci o prostoru, usluge, datumi, procena cene i podaci narudžbine. Čuvamo istoriju razgovora i priložene slike ili datoteke. Šaljite samo potrebne informacije, bez ličnih dokumenata, podataka za plaćanje ili osetljivih slika."},
      {title: "Svrhe obrade", text: "Podatke koristimo za odgovore, procenu cene, zakazivanje, izvršavanje narudžbina i podršku. Identifikatori poruka, potvrde isporuke, vremenske oznake, podaci sesije i bezbednosni zapisi omogućavaju komunikaciju, sprečavanje duplikata i zaštitu servisa."},
      {title: "WhatsApp i Meta", text: "Naš WhatsApp kanal koristi WhatsApp Business Platform kompanije Meta. Poruke i događaji isporuke obrađuju se kroz Meta i naš servis. Meta obrađuje podatke i prema svojim pravilima. Brisanje kopije iz LumaClean ne briše vaš WhatsApp nalog niti kopije kod vas ili kompanije Meta."},
      {title: "AI i pružaoci usluga", text: "Automatizovani AI pomoćnik može obrađivati neke poruke i slike radi razumevanja upita, pripreme odgovora ili pomoći pri zakazivanju. Možete zatražiti razgovor sa osobom. Neophodne podatke obrađuju pružaoci hostinga, baze podataka, skladištenja, komunikacije i AI usluga, uključujući Vercel, Neon, Meta, PoYo i OpenRouter. Podatke delimo radi rada servisa, a ne objavljujemo razgovore. Pružaoci mogu obrađivati podatke izvan Srbije prema svojim uslovima i politikama privatnosti."},
      {title: "Analitika sajta", text: "Opciona Google Analytics učitava se tek nakon dozvole u podešavanjima privatnosti. Prima podatke o stranicama, radnjama i uređaju i može koristiti kolačiće. Tekst upita, imena i brojeve telefona ne šaljemo analitici. Izbor možete promeniti u podešavanjima privatnosti na sajtu."},
      {title: "Čuvanje i bezbednost", text: "Čuvamo informacije potrebne za upite, aktivne narudžbine, podršku i neophodne operativne ili pravne evidencije. Trajanje zavisi od svrhe i zahteva za brisanje; nema jednog fiksnog roka za svaki zapis. Administratorski pristup je ograničen, prilozi se čuvaju privatno, a pristupni podaci na serveru. Nijedan sistem ne garantuje apsolutnu bezbednost. Rezervne kopije mogu ostati do zamene ili isteka u redovnom ciklusu."},
      {title: "Vaši zahtevi", text: "Kontaktirajte nas za informacije o svojim podacima, ispravku ili brisanje. Možda ćemo proveriti da li zahtev obuhvata vaše podatke. Neki zapisi moraju ostati zbog aktivne narudžbine, spora ili važećih obaveza; objasnićemo ograničenja. Koristite uputstvo za brisanje ili kontakte navedene ispod."},
    ],
    steps: [
      {title: "1. Kontaktirajte nas", text: "Pišite LumaClean putem WhatsApp veze ispod i zatražite brisanje svojih podataka. Ako kanal nije dostupan, pozovite objavljeni kontakt broj radi dogovora o drugom načinu zahteva."},
      {title: "2. Navedite podatke", text: "Navedite broj telefona ili kanal kojim ste kontaktirali LumaClean i podatke za brisanje, poput razgovora, priloga ili upita. Ako imate, dodajte oznaku narudžbine ili približan datum razgovora. Ne šaljite lozinke, tokene ili lične dokumente u početnom zahtevu."},
      {title: "3. Provera", text: "Administrator proverava zahtev i po potrebi traži potvrdu pristupa izvornom kanalu. Proveravamo šta se može obrisati i da li aktivna narudžbina, spor ili obavezna evidencija sprečavaju trenutno brisanje pojedinih zapisa."},
      {title: "4. Završetak", text: "Brišemo podatke koji mogu biti obrisani iz aktivnih evidencija i po potrebi kontaktiramo relevantne pružaoce usluga. Potvrdićemo rezultat ili objasniti šta se zadržava i zašto. Rezervne kopije ne moraju biti uklonjene odmah; zamenjuju se ili ističu prema ciklusu. Zahtev ne briše WhatsApp nalog niti kopije kojima upravlja Meta ili drugi učesnici."},
    ],
  },
} satisfies Record<Locale, LegalCopy>;
