import type {Locale} from "@/i18n/routing";

const ru = {
  nav: {services: "Услуги", prices: "Цены", process: "Как работаем", cta: "Получить расчёт", shortCta: "Расчёт", navLabel: "Основная навигация", languageLabel: "Выбор языка"},
  handoff: {kicker: "Маршрут 04 / 04 · Кухня", title: <>Теперь —<br/>по делу.</>, body: "Пространство уже рассказало, что мы чистим. Дальше — точный объём работ, прозрачная цена и понятный результат.", scroll: "Листайте, чтобы открыть сервисное досье"},
  scope: {number: "01 · Объём", title: <>Два уровня внимания<br/>к пространству.</>, body: "Поддерживающая подходит для регулярного ухода. Генеральная — когда нужно больше времени на кухню, санузел и труднодоступные зоны.", regular: "A", deep: "B"},
  rates: {number: "02 · Ведомость цен", title: <>Цена понятна<br/>до заявки.</>, body: "Выберите тип уборки и площадь. Получите понятный ориентир без скрытых пакетов и обязательных дополнений.", link: "Собрать свой расчёт", focus: "Выбранный ориентир", type: "Тип", area: "Площадь", service: "Услуга", swipe: "Проведите в сторону, чтобы увидеть все площади"},
  materials: {number: "03 · Дополнительные работы", title: <>Не пакет.<br/>Конкретная работа.</>, body: "Добавляйте только то, что действительно требуется квартире. Каждая работа отдельно отображается в расчёте.", mirror: "Окна и стеклянные поверхности", steam: "Eco steam", appliance: "Шкафы внутри"},
  method: {number: "04 · Маршрут работы", title: <>От сообщения<br/>до чистого дома.</>, body: "Уточняем задачу, фиксируем цену, согласуем время и проверяем результат вместе с вами."},
  evidence: {number: "05 · Условия", title: <>Спокойствие строится<br/>на конкретике.</>, body: "Заранее фиксируем цену, формат работы, средства и границы услуги — без сюрпризов после уборки."},
  faq: {number: "06 · Коротко о важном", title: <>Вопросы до<br/>первой уборки.</>, body: "Цена, средства, окна, оплата и срочный выезд — всё, что важно знать до заявки."},
  estimate: {number: "07 · Расчёт", title: <>Соберите уборку.<br/>Увидьте состав цены.</>, body: "Расчёт обновляется сразу при выборе площади и дополнительных работ. Финальную цену подтвердим после короткого описания или фото.", service: "Тип уборки", area: "Площадь", extras: "Дополнительные работы", reference: "Ориентир", calculation: "Расчёт LC-026", city: "Белград", total: "Ориентировочно", toReceipt: "К расчёту", note: "Подтвердим стоимость до начала работы. Оплата после проверки результата.", name: "Ваше имя", phone: "Телефон / мессенджер", comment: "Комментарий", commentHint: "Необязательно: район, желаемая дата или особенности квартиры", consent: "Согласен на обработку данных", send: "Отправить расчёт", sending: "Отправляем…", success: "Расчёт отправлен. Скоро свяжемся с вами.", validation: "Заполните имя, телефон и подтвердите согласие.", error: "Не удалось отправить. Напишите нам в мессенджер или попробуйте ещё раз."},
  closing: {number: "Готовы начать?", title: <>Результат скажет<br/>сам за себя.</>, body: "Укажите площадь и оставьте контакт. Мы уточним детали, при необходимости попросим несколько фото, подтвердим цену и предложим ближайшее удобное время.", cta: "Получить расчёт", direct: "Или выберите удобный мессенджер"},
  footer: "Белград · 2026",
};

const sr = {
  nav: {services: "Usluge", prices: "Cene", process: "Kako radimo", cta: "Dobijte procenu", shortCta: "Procena", navLabel: "Glavna navigacija", languageLabel: "Izbor jezika"},
  handoff: {kicker: "Ruta 04 / 04 · Kuhinja", title: <>Sada —<br/>konkretno.</>, body: "Prostor je već pokazao šta čistimo. Sledi precizan obim rada, jasna cena i očekivani rezultat.", scroll: "Skrolujte da otvorite servisni dosije"},
  scope: {number: "01 · Obim", title: <>Dva nivoa pažnje<br/>prema prostoru.</>, body: "Održavajuće čišćenje je za redovnu negu. Generalno je za kuhinju, kupatilo i zahtevne zone kojima treba više vremena.", regular: "A", deep: "B"},
  rates: {number: "02 · Cenovnik", title: <>Cena je jasna<br/>pre upita.</>, body: "Izaberite vrstu čišćenja i kvadraturu. Dobićete jasan okvir bez skrivenih paketa i obaveznih dodataka.", link: "Sastavite svoj obračun", focus: "Izabrani okvir", type: "Vrsta", area: "Površina", service: "Usluga", swipe: "Prevucite u stranu da vidite sve kvadrature"},
  materials: {number: "03 · Dodatni radovi", title: <>Ne paket.<br/>Konkretan rad.</>, body: "Dodajte samo ono što je stanu zaista potrebno. Svaki dodatni rad se posebno vidi u obračunu.", mirror: "Prozori i staklene površine", steam: "Eco steam", appliance: "Ormarići iznutra"},
  method: {number: "04 · Tok rada", title: <>Od poruke<br/>do čistog doma.</>, body: "Proveravamo zadatak, potvrđujemo cenu, dogovaramo vreme i zajedno pregledamo rezultat."},
  evidence: {number: "05 · Uslovi", title: <>Mir se gradi<br/>na konkretnim stvarima.</>, body: "Unapred potvrđujemo cenu, način rada, sredstva i granice usluge — bez iznenađenja nakon čišćenja."},
  faq: {number: "06 · Važne informacije", title: <>Pitanja pre<br/>prvog čišćenja.</>, body: "Cena, sredstva, prozori, plaćanje i hitni dolazak — sve što treba da znate pre upita."},
  estimate: {number: "07 · Obračun", title: <>Sastavite čišćenje.<br/>Vidite sastav cene.</>, body: "Procena se menja odmah sa kvadraturom i dodatnim radovima. Konačnu cenu potvrđujemo nakon kratkog opisa ili fotografija.", service: "Vrsta čišćenja", area: "Površina", extras: "Dodatni radovi", reference: "Okvir", calculation: "Obračun LC-026", city: "Beograd", total: "Okvirno", toReceipt: "Pogledaj procenu", note: "Potvrđujemo cenu pre početka. Plaćanje nakon provere rezultata.", name: "Vaše ime", phone: "Telefon / mesindžer", comment: "Komentar", commentHint: "Opciono: deo grada, željeni datum ili posebne napomene", consent: "Saglasan/na sam sa obradom podataka", send: "Pošalji procenu", sending: "Šaljemo…", success: "Procena je poslata. Uskoro ćemo vam se javiti.", validation: "Unesite ime i telefon i potvrdite saglasnost.", error: "Slanje nije uspelo. Pišite nam ili pokušajte ponovo."},
  closing: {number: "Spremni?", title: <>Rezultat govori<br/>sam za sebe.</>, body: "Unesite kvadraturu i ostavite kontakt. Proverićemo detalje, po potrebi zatražiti fotografije, potvrditi cenu i predložiti najbliži termin.", cta: "Dobijte procenu", direct: "Ili izaberite mesindžer"},
  footer: "Beograd · 2026",
};

const en = {
  nav: {services: "Services", prices: "Prices", process: "How it works", cta: "Get an estimate", shortCta: "Estimate", navLabel: "Primary navigation", languageLabel: "Choose language"},
  handoff: {kicker: "Route 04 / 04 · Kitchen", title: <>Now —<br/>the details.</>, body: "The space has shown what we clean. Next comes the exact scope, transparent pricing and a clear outcome.", scroll: "Scroll to open the service dossier"},
  scope: {number: "01 · Scope", title: <>Two levels of care<br/>for your space.</>, body: "Regular cleaning is for ongoing care. Deep cleaning gives the kitchen, bathroom and difficult areas the extra time they need.", regular: "A", deep: "B"},
  rates: {number: "02 · Price ledger", title: <>See the price<br/>before you enquire.</>, body: "Choose a cleaning type and area for a clear guide with no hidden packages or compulsory extras.", link: "Build your estimate", focus: "Selected guide", type: "Type", area: "Area", service: "Service", swipe: "Swipe sideways to see every area range"},
  materials: {number: "03 · Extra work", title: <>Not a package.<br/>Specific work.</>, body: "Add only what the home genuinely needs. Every extra appears separately in the estimate.", mirror: "Windows and glass surfaces", steam: "Eco steam", appliance: "Inside cabinets"},
  method: {number: "04 · The route", title: <>From a message<br/>to a clean home.</>, body: "We confirm the task and price, agree a time and review the result with you."},
  evidence: {number: "05 · Terms", title: <>Peace of mind rests<br/>on specifics.</>, body: "We confirm the price, working method, products and service boundaries upfront — no surprises after cleaning."},
  faq: {number: "06 · The essentials", title: <>Questions before<br/>your first clean.</>, body: "Pricing, products, windows, payment and urgent visits — what you need to know before enquiring."},
  estimate: {number: "07 · Estimate", title: <>Build your cleaning.<br/>See every part of the price.</>, body: "The estimate updates as you change the area and extras. We confirm the final price after a short description or photos.", service: "Cleaning type", area: "Area", extras: "Extra work", reference: "Estimate", calculation: "Estimate LC-026", city: "Belgrade", total: "Estimated total", toReceipt: "View estimate", note: "We confirm the price before starting. Pay after checking the result.", name: "Your name", phone: "Phone / messenger", comment: "Comment", commentHint: "Optional: district, preferred date or anything we should know", consent: "I agree to the processing of my data", send: "Send estimate", sending: "Sending…", success: "Estimate sent. We’ll contact you shortly.", validation: "Enter your name and phone, then confirm consent.", error: "Could not send. Message us directly or try again."},
  closing: {number: "Ready to begin?", title: <>The result speaks<br/>for itself.</>, body: "Enter the area and leave your contact details. We’ll check the details, request photos if needed, confirm the price and offer the nearest suitable time.", cta: "Get an estimate", direct: "Or choose your preferred messenger"},
  footer: "Belgrade · 2026",
};

export const editorialContent: Record<Locale, typeof ru | typeof sr | typeof en> = {ru, sr, en};
export type EditorialContent = (typeof editorialContent)[Locale];
