import {basePrice, extrasPrices, formatRsd, priceAreaLabels, priceMatrix} from "@/lib/pricing";
import type {Locale} from "@/i18n/routing";
import type {Article} from "./types";

function priceRows(locale: Locale) {
  const unit = {ru: " / м²", sr: " / m²", en: " / m²"}[locale];
  return priceAreaLabels[locale].map((area, index) => [area,
    ...(["regular", "deep", "move"] as const).map(service => formatRsd(priceMatrix[service][index], locale) + (index === 4 ? unit : "")),
  ]);
}

export const cost: Article = {
  id: "cost", status: "published", publishedAt: "2026-09-15", updatedAt: "2026-09-29", image: "/media/articles/cost.webp", services: ["regular", "deep", "move"],
  relatedIds: ["choose","windows","duration"],
  translations: {
    ru: {
      slug: "stoimost-uborki-kvartiry-v-belgrade", title: "От чего зависит стоимость уборки квартиры в Белграде",
      description: "Что влияет на расчёт уборки в Белграде: площадь, формат, состояние квартиры и дополнительные работы. Пример из действующего калькулятора LumaClean.",
      category: "Стоимость", imageAlt: "Иллюстрация макета квартиры и складной линейки на деревянном столе",
      lead: "У двух предложений на уборку одной квартиры может быть разная цена — и разный список работ. Где-то посчитали только полы и доступные поверхности, а где-то добавили окна и духовку. Разберём, как устроен расчёт LumaClean и что стоит уточнить перед заказом.",
      sections: [
        {id: "price-list", title: "Базовый прайс LumaClean по площади", paragraphs: ["Это действующие базовые суммы LumaClean, а не средняя цена по Белграду. Для площади до 100 м² указана сумма за уборку; в последней строке — ставка за квадратный метр. Окна и другие дополнения в таблицу не включены. Итоговую стоимость подтверждаем после согласования состояния квартиры и списка работ.", "Диапазоны действуют по порогам 40, 60, 80 и 100 м²: например, 59,5 м² остаются в группе 40–59 м², а 60 м² переходят в следующую. От 100 м² сумма округляется до ближайших 100 RSD. Проверьте свой расчёт в калькуляторе перед отправкой заявки."], table: {caption: "Базовые цены на 29 сентября 2026 года", headings: ["Площадь", "Поддерживающая", "Генеральная", "При переезде"], rows: priceRows("ru")}},
        {id: "area", title: "Площадь и основной формат", paragraphs: ["В калькуляторе LumaClean базовая стоимость зависит от площади и типа уборки. Для квартир меньше 100 м² используются диапазоны площади, а от 100 м² — расчёт по ставке выбранной услуги с округлением. Поэтому небольшое изменение площади внутри одного диапазона не всегда меняет сумму.", "Поддерживающая, генеральная и уборка при переезде решают разные задачи. Сравнивайте одинаковые форматы и состав работ: более низкая исходная цифра может относиться к другому объёму. Укажите фактическую площадь квартиры, а не только комнаты, в которой сейчас больше всего работы."]},
        {id: "example", title: "Пример из калькулятора, а не обещание итоговой цены", paragraphs: [`Для квартиры 55 м² базовая поддерживающая уборка в текущем калькуляторе стоит ${formatRsd(basePrice("regular", 55), "ru")}. Если добавить мойку духовки внутри за ${formatRsd(extrasPrices.oven, "ru")}, предварительная сумма составит ${formatRsd(basePrice("regular", 55) + extrasPrices.oven, "ru")}. Это пример для этих двух позиций, без других дополнительных работ.`, "Чтобы получить расчёт для своей квартиры, выберите услуги в калькуляторе и отправьте описание или фотографии. До начала уборки мы подтвердим сумму и договоримся о времени."], tip: "Сравнивая две оценки, выпишите рядом площадь, формат и дополнительные работы. Так будет видно, действительно ли вам предлагают одно и то же."},
        {id: "extras", title: "Что добавляется к базовой стоимости", paragraphs: ["Окна, балкон, внутренние поверхности холодильника, духовки и шкафов выбираются отдельно. В калькуляторе также есть другие дополнительные задачи, например глажка и удаление шерсти животных. Выберите то, что нужно именно сейчас, и уточните количество там, где оно предусмотрено.", "Чтобы мы могли оценить состояние квартиры, пришлите фотографии кухни, ванной и мест, которые трудно отмыть. Если нужен визит в день обращения, он возможен только при наличии свободного слота; на сайте для срочного выезда указана доплата 20%. Сначала подтвердите доступность."], bullets: ["Уточните, какие окна нужно вымыть и есть ли большие створки.", "Отдельно перечислите технику и шкафы для мойки внутри.", "Сообщите о животных и заметной шерсти.", "Укажите желаемую дату, особенно если уборка нужна сегодня."]},
        {id: "request", title: "Как получить полезный расчёт с первого сообщения", paragraphs: ["Напишите площадь, район Белграда, тип уборки и главные пожелания. Приложите несколько понятных фотографий вместо большого набора одинаковых кадров. Отметьте, живут ли сейчас в квартире, осталась ли мебель и связана ли уборка с переездом.", "Сохраните согласованный список работ и сумму в переписке. Предоплата не нужна; уборку оплачивают наличными после завершения. Если хотите что-то добавить к заказу, обсудите это до визита — так у команды будет время учесть новую задачу."]},
      ],
    },
    sr: {
      slug: "od-cega-zavisi-cena-ciscenja-stana-beograd", title: "Od čega zavisi cena čišćenja stana u Beogradu",
      description: "Površina, vrsta čišćenja i dodatni poslovi: kako se formira procena za stan u Beogradu, uz primer iz važećeg LumaClean kalkulatora.",
      category: "Cena", imageAlt: "Ilustracija makete stana i sklopivog lenjira na drvenom stolu",
      lead: "Cena po kvadratnom metru nije dovoljna za poređenje ponuda. Prvo proverite koje poslove procena pokriva. Isti stan može tražiti uobičajeno održavanje ili temeljnije čišćenje pre useljenja.",
      sections: [
        {id: "price-list", title: "Osnovni LumaClean cenovnik prema površini", paragraphs: ["Ovo su važeće osnovne cene LumaClean usluga, a ne prosečne cene u Beogradu. Za površine manje od 100 m² prikazan je iznos po čišćenju; poslednji red sadrži cenu po kvadratnom metru. Prozori i drugi dodatni poslovi nisu uključeni. Konačnu cenu potvrđujemo nakon dogovora o stanju stana i obimu posla.", "Granice raspona su 40, 60, 80 i 100 m²: na primer, 59,5 m² pripada rasponu 40–59 m², a 60 m² sledećem rasponu. Od 100 m² iznos se zaokružuje na najbližih 100 RSD. Proverite procenu za vaš stan u kalkulatoru pre slanja upita."], table: {caption: "Osnovne cene na dan 29. septembra 2026.", headings: ["Površina", "Redovno", "Generalno", "Pri selidbi"], rows: priceRows("sr")}},
        {id: "area", title: "Površina i osnovna usluga", paragraphs: ["U LumaClean kalkulatoru osnovna cena zavisi od površine i vrste čišćenja. Za stanove manje od 100 m² koriste se rasponi površine, a od 100 m² obračun po stopi izabrane usluge uz zaokruživanje. Mala razlika unutar istog raspona zato ne mora promeniti iznos.", "Redovno, generalno i čišćenje pri selidbi namenjeni su različitim potrebama. Poredite isti format i obim: niža početna cifra može podrazumevati drugačiji posao. Navedite stvarnu površinu stana, a ne samo sobe kojoj trenutno treba najviše pažnje."]},
        {id: "example", title: "Primer iz kalkulatora, ne konačna ponuda", paragraphs: [`Za stan od 55 m² osnovno redovno čišćenje u trenutnom kalkulatoru iznosi ${formatRsd(basePrice("regular", 55), "sr")}. Uz čišćenje unutrašnjosti rerne od ${formatRsd(extrasPrices.oven, "sr")}, okvirni zbir je ${formatRsd(basePrice("regular", 55) + extrasPrices.oven, "sr")}. Primer obuhvata samo te dve stavke, bez drugih dodataka.`, "Za procenu vašeg stana izaberite usluge u kalkulatoru i pošaljite opis ili fotografije. Pre čišćenja potvrdićemo cenu i dogovoriti termin."], tip: "Uz dve procene zapišite površinu, vrstu čišćenja i dodatne poslove. Tek tada možete da vidite da li ponude pokrivaju isto."},
        {id: "extras", title: "Šta se dodaje osnovnoj ceni", paragraphs: ["Prozori, balkon i unutrašnjost frižidera, rerne i ormara biraju se zasebno. Kalkulator sadrži i druge dodatke, kao što su peglanje i uklanjanje dlaka kućnih ljubimaca. Izaberite potrebne stavke i proverite količinu tamo gde je predviđena.", "Stanje stana pomaže da se odredi odgovarajući format i obim. Pošaljite fotografije kuhinje, kupatila i zahtevnijih mesta. Dolazak istog dana moguć je samo ako postoji slobodan termin; sajt navodi doplatu od 20% za hitan dolazak. Dostupnost prvo treba potvrditi."], bullets: ["Navedite prozore i velike otvore koje treba oprati.", "Odvojeno popišite uređaje i ormariće za čišćenje iznutra.", "Pomenite ljubimce i primetne dlake.", "Napišite željeni datum, naročito ako vam treba današnji termin."]},
        {id: "request", title: "Šta poslati za korisnu procenu", paragraphs: ["Pošaljite površinu, deo Beograda, vrstu čišćenja i glavne prioritete. Dodajte nekoliko jasnih fotografija umesto više gotovo istih kadrova. Recite da li se u stanu živi, ima li nameštaja i da li je čišćenje vezano za selidbu.", "Sačuvajte dogovoreni spisak poslova i cenu u prepisci. Avans nije potreban; plaća se gotovinom po završetku. Ako želite da dodate nešto, javite pre dolaska kako bi tim mogao da isplanira i taj posao."]},
      ],
    },
    en: {
      slug: "apartment-cleaning-cost-belgrade", title: "What affects apartment cleaning prices in Belgrade?",
      description: "Understand cleaning estimates in Belgrade: floor area, service type, apartment condition and extras, with an example from the LumaClean calculator.",
      category: "Pricing", imageAlt: "Conceptual illustration of an apartment scale model and folding ruler on a wooden table",
      lead: "A price per square metre is not enough to compare cleaning quotes. First check which tasks the estimate covers. The same apartment may need routine maintenance or more thorough attention before a move.",
      sections: [
        {id: "price-list", title: "LumaClean base prices by floor area", paragraphs: ["These are LumaClean's current base prices, not market averages for Belgrade. For areas below 100 m², each amount is per clean; the final row gives the rate per square metre. Windows and other extras are not included. We confirm the final price after agreeing the apartment's condition and scope of work.", "The band thresholds are 40, 60, 80 and 100 m²: for example, 59.5 m² stays in the 40–59 m² band, while 60 m² moves to the next band. From 100 m², the amount is rounded to the nearest 100 RSD. Check your own estimate in the calculator before sending an enquiry."], table: {caption: "Base prices as of 29 September 2026", headings: ["Floor area", "Regular", "Deep", "Moving"], rows: priceRows("en")}},
        {id: "area", title: "Floor area and the base service", paragraphs: ["LumaClean's calculator uses floor area and the cleaning type to determine the base price. Apartments below 100 m² use area bands; from 100 m² the selected service's area rate applies with rounding. A small difference within the same band may therefore leave the price unchanged.", "Regular, deep and moving services address different needs. Compare the same service and scope: a lower starting figure may cover a different job. Give the apartment's actual floor area, rather than only the room that currently needs the most attention."]},
        {id: "example", title: "A calculator example, not a final quotation", paragraphs: [`For a 55 m² apartment, the current calculator's base regular cleaning price is ${formatRsd(basePrice("regular", 55), "en")}. Adding internal oven cleaning at ${formatRsd(extrasPrices.oven, "en")} gives an indicative total of ${formatRsd(basePrice("regular", 55) + extrasPrices.oven, "en")}. This example includes only those two items, with no other extras.`, "For your own estimate, select the services in the calculator and send a description or photographs. We will confirm the price and agree an appointment before cleaning starts."], tip: "Write the area, service type and extras beside each estimate you compare. This shows whether the quotes actually cover the same work."},
        {id: "extras", title: "What adds to the base price", paragraphs: ["Windows, the balcony and the insides of the fridge, oven and cupboards are selected separately. The calculator also offers tasks such as ironing and pet hair removal. Select what you need and confirm quantities where applicable.", "The condition of the apartment helps establish the right service and scope. Send photographs of the kitchen, bathroom and difficult areas. A same-day visit is possible only when a slot is available; the site lists a 20% surcharge for urgent attendance. Availability must be confirmed first."], bullets: ["Identify the windows, including larger openings, that need washing.", "List appliances and cupboards for internal cleaning separately.", "Mention pets and noticeable pet hair.", "Include your preferred date, especially for a same-day request."]},
        {id: "request", title: "What to send for a useful estimate", paragraphs: ["Include the floor area, Belgrade neighbourhood, service type and main priorities. Add a few clear photographs rather than many similar shots. Mention whether the apartment is occupied or furnished and whether the cleaning is for a move.", "Keep the agreed task list and price in your messages. No deposit is needed; payment is in cash after completion. If you would like to add something, discuss it before the visit so the team can plan for the extra work."]},
      ],
    },
  },
};
