import type {Article} from "./types";

export const moveIn: Article = {
  id: "move-in", status: "published", publishedAt: "2026-09-15", updatedAt: "2026-09-15", image: "/media/articles/move-in.webp", services: ["move", "deep"],
  relatedIds: ["move-out","windows","prepare"],
  translations: {
    ru: {
      slug: "podgotovit-kvartiru-k-uborke-pered-vezdom", title: "Как подготовить квартиру к уборке перед въездом",
      description: "План уборки перед въездом в квартиру в Белграде: когда назначить визит, что проверить после передачи ключей и какие работы согласовать заранее.",
      category: "Переезд", imageAlt: "Иллюстрация пустой квартиры, коробок и ключа в бирюзовой чаше",
      lead: "Убирать перед въездом удобнее, пока вещи ещё в коробках, а полки и пол доступны. Несколько простых договорённостей помогут не переносить визит и не мыть заново то, что уже успели заставить мебелью.",
      sections: [
        {id: "timing", title: "Выберите момент между ключами и коробками", paragraphs: ["По возможности назначьте уборку после передачи квартиры и до доставки основной части вещей. К этому моменту прежние жильцы должны закончить вывоз, а вы — получить доступ во все комнаты. Если доставка мебели и уборка совпадут, согласуйте порядок работ заранее: одновременно занятые проходы мешают и грузчикам, и клинерам.", "Проверьте, что в квартире есть вода, электричество и возможность открыть дверь в оговорённое время. Уточните домофон, этаж и порядок доступа. Если ключ передаёт владелец или агент, лучше заранее договориться, кто встретит команду и кому звонить при задержке."]},
        {id: "inspect", title: "Осмотрите квартиру до уборки", paragraphs: ["Пройдите кухню и санузел, откройте доступные шкафы и оцените состояние техники. Сфотографируйте заметные повреждения и обсудите их с владельцем отдельно: царапина на столешнице или потёртая затирка не обязательно исчезнут после мытья.", "Для заявки полезны общие фотографии комнат и крупные планы мест, которым нужно внимание. Сообщите, остались ли вещи предыдущих жильцов. Не выбрасывайте их без согласования и не рассчитывайте, что команда сама определит, что можно убрать из квартиры."], bullets: ["Работают ли вода и электричество?", "Освободились ли шкафы, которые нужно вымыть внутри?", "Есть ли особые покрытия и инструкции владельца по уходу?", "Завершены ли работы мастеров и вывоз вещей?"]},
        {id: "scope", title: "Составьте список внутренних поверхностей", paragraphs: ["Перед въездом легко забыть места, которые скоро будут заняты: полки с посудой, ящики, холодильник. В LumaClean внутреннее мытьё шкафов, холодильника и духовки, а также окна и балкон выбираются дополнительно. Перечислите нужные задачи при согласовании услуги для переезда.", "Если квартира уже частично обставлена, освободите только те зоны, которые вошли в заказ. Для холодильника заранее договоритесь, куда убрать продукты. Не требуется складывать всё в одну комнату: лучше оставить понятные свободные проходы и обозначить коробки, которые нельзя перемещать."], tip: "Составьте короткий список «до распаковки»: кухонные полки, нужные ящики, холодильник. Согласовать их сейчас проще, чем освобождать после расстановки вещей."},
        {id: "limits", title: "Отделите переезд от ремонта", paragraphs: ["Уборка перед въездом и уборка после строительных работ — разные задачи. LumaClean не предлагает уборку после ремонта, устранение плесени или последствий затопления. Если вы видите строительную пыль, остатки краски или такие повреждения, опишите их до заказа, чтобы не выбирать неподходящую услугу.", "В день визита покажите согласованные зоны и приоритеты. После завершения пройдите квартиру вместе с командой, пока полки ещё пустые. Затем можно распаковывать вещи, начиная с кухни и предметов первой необходимости. Чистые полки лучше заполнить сразу, пока коробки не заняли все проходы."]},
      ],
    },
    sr: {
      slug: "priprema-stana-za-ciscenje-pre-useljenja", title: "Kako pripremiti stan za čišćenje pre useljenja",
      description: "Praktičan redosled pre useljenja u Beogradu: termin čišćenja, primopredaja ključeva, prazne police i dodatni poslovi koje treba dogovoriti.",
      category: "Selidba", imageAlt: "Ilustracija praznog stana, kutija i ključa u tirkiznoj posudi",
      lead: "Stan je lakše očistiti pre nego što police napunite stvarima. Dobar trenutak i kratak dogovor o pristupu znače manje pomeranja kutija i manje ponavljanja posla tokom selidbe.",
      sections: [
        {id: "timing", title: "Između preuzimanja ključeva i dolaska stvari", paragraphs: ["Ako možete, zakažite čišćenje posle primopredaje stana, a pre dolaska većine stvari. Prethodni stanari treba da završe iznošenje, a sve prostorije da budu dostupne. Ako nameštaj stiže istog dana, unapred uskladite redosled: zauzeti prolazi otežavaju oba posla.", "Proverite vodu, struju i pristup u dogovoreno vreme. Pošaljite podatke o interfonu, spratu i ulazu. Ako ključ predaje vlasnik ili agent, dogovorite ko dočekuje tim i koga treba pozvati ako nešto kasni."]},
        {id: "inspect", title: "Pregledajte stan pre početka", paragraphs: ["Pogledajte kuhinju i kupatilo, otvorite dostupne ormariće i proverite uređaje. Fotografije postojećih oštećenja odvojeno razmotrite sa vlasnikom. Ogrebotina na radnoj ploči ili istrošena fuga ne moraju nestati čišćenjem.", "Za procenu pošaljite opšte fotografije prostorija i detalje mesta kojima treba pažnja. Recite da li su ostale stvari prethodnih stanara. Nemojte ih bacati bez dogovora niti očekivati da tim odlučuje šta sme da se ukloni."], bullets: ["Da li rade voda i struja?", "Da li su ormarići predviđeni za unutrašnje čišćenje prazni?", "Postoje li posebne površine ili uputstva vlasnika?", "Da li su majstori i iznošenje stvari završili?"]},
        {id: "scope", title: "Dogovorite unutrašnje površine", paragraphs: ["Lako je prevideti police za posuđe, fioke i frižider dok razmišljate o selidbi. Kod LumaClean-a unutrašnjost ormara, frižidera i rerne, kao i prozori i balkon, biraju se dodatno. Navedite potrebne poslove uz čišćenje za useljenje ili iseljenje.", "Ako je stan delimično opremljen, oslobodite dogovorene zone. Unapred isplanirajte gde će hrana stajati dok se čisti frižider. Nije potrebno sve nagurati u jednu sobu: ostavite jasne prolaze i obeležite kutije koje ne treba pomerati."], tip: "Napravite kratak spisak poslova pre raspakivanja: kuhinjske police, odabrane fioke i frižider. Lakše ih je dogovoriti dok su još prazni."},
        {id: "limits", title: "Useljenje nije isto što i završetak renoviranja", paragraphs: ["Čišćenje pre useljenja razlikuje se od uklanjanja posledica građevinskih radova. LumaClean ne nudi čišćenje posle renoviranja, uklanjanje buđi ili posledica poplave. Ako postoji građevinska prašina ili ostaci boje, opišite stanje pre rezervacije.", "Na dan dolaska pokažite dogovorene zone i prioritete. Po završetku zajedno pregledajte stan dok su police još prazne, pa raspakujte kuhinju i neophodne stvari. Popunite čiste police pre nego što kutije ponovo zauzmu prolaze."]},
      ],
    },
    en: {
      slug: "prepare-apartment-for-move-in-cleaning", title: "How to prepare an apartment for move-in cleaning",
      description: "Plan cleaning before moving into a Belgrade apartment: key handover, access, empty cupboards and the additional tasks to agree before your visit.",
      category: "Moving home", imageAlt: "Conceptual illustration of an empty apartment, moving boxes and a key in a turquoise dish",
      lead: "An apartment is easier to clean before cupboards fill up and boxes cover the floor. A little planning around the handover helps avoid moving things twice or cleaning surfaces that immediately become blocked again.",
      sections: [
        {id: "timing", title: "Book between the key handover and the boxes", paragraphs: ["Where possible, arrange cleaning after you receive the apartment and before most belongings arrive. The previous occupants should have finished moving out, and every room should be accessible. If furniture delivery is on the same day, agree the sequence in advance: blocked doorways make both jobs harder.", "Check that water and electricity are available and that someone can open the door at the agreed time. Share the intercom details, floor and entrance instructions. If a landlord or agent holds the key, agree who will meet the team and who to contact if there is a delay."]},
        {id: "inspect", title: "Look around before cleaning starts", paragraphs: ["Check the kitchen, bathroom, accessible cupboards and appliances. Photograph existing damage and discuss it separately with the landlord. A scratched worktop or worn grout may not change after cleaning.", "For the enquiry, send overall room photographs and close-ups of areas needing attention. Mention anything the previous occupants left behind. Do not dispose of their possessions without agreement or expect the cleaning team to decide what can leave the apartment."], bullets: ["Are water and electricity working?", "Are cupboards booked for internal cleaning empty?", "Are there special surfaces or care instructions from the owner?", "Have tradespeople and movers finished their work?"]},
        {id: "scope", title: "List the inside surfaces you need cleaned", paragraphs: ["Kitchen shelves, drawers and the fridge are easy to overlook during a move. LumaClean offers the insides of cupboards, the fridge and oven, along with windows and the balcony, as additional tasks. List what you need when arranging the moving service.", "If the apartment is partly furnished, clear the agreed areas. Plan where to put food while the fridge is cleaned. You do not need to squeeze everything into one room: leave usable walkways and identify boxes that should stay where they are."], tip: "Make a short before-unpacking list: kitchen shelves, selected drawers and the fridge. It is easier to arrange these tasks while the spaces are empty."},
        {id: "limits", title: "Separate moving from renovation work", paragraphs: ["Move-in cleaning is different from cleaning up after building work. LumaClean does not offer post-renovation cleaning, mould removal or flood recovery. If you notice construction dust or paint residue, describe it before booking so the service can be assessed correctly.", "On the day, show the team the agreed areas and priorities. Walk through together afterwards while the shelves are still empty, then unpack the kitchen and essentials. Fill the clean shelves before boxes take over the walkways again."]},
      ],
    },
  },
};
