import type {Article} from "./types";

export const prepare: Article = {
  id: "prepare", status: "published", publishedAt: "2026-09-15", updatedAt: "2026-09-15", image: "/media/articles/prepare.webp", services: ["regular", "deep"],
  relatedIds: ["pet-hair","duration","choose"],
  translations: {
    ru: {
      slug: "kak-podgotovitsya-k-priezdu-klinerov", title: "Как подготовиться к приезду клинеров",
      description: "Что сделать перед уборкой: освободить поверхности, согласовать доступ, убрать личные вещи и сообщить о приоритетах. Короткий список для клиентов LumaClean.",
      category: "Перед визитом", imageAlt: "Иллюстрация свободной столешницы с аккуратно собранными мелочами и сложенной тканью",
      lead: "Перед уборкой достаточно собрать личные вещи, освободить проходы и договориться, кто откроет дверь. Ниже — список того, что действительно стоит сделать до приезда команды.",
      sections: [
        {id: "clear", title: "Освободите то, что предстоит мыть", paragraphs: ["Соберите одежду, бумаги и мелкие личные вещи с пола и рабочих поверхностей. Не требуется идеально раскладывать всё по шкафам: достаточно убрать в заранее выбранное место то, что мешает доступу. Так клинерам не придётся спрашивать, куда положить каждую вещь.", "Если согласована мойка шкафа внутри, освободите нужные полки. Для духовки и холодильника уточните подготовку заранее; продумайте, куда временно убрать содержимое. Не передвигайте тяжёлую мебель ради обычного визита — лучше заранее обсудить доступ к участкам за ней."], tip: "Начните с кухонной столешницы, раковины, пола и полок, вошедших в заказ. Не тратьте время на уборку зон, которые клинеры должны вымыть сами."},
        {id: "personal", title: "Отложите личные вещи и объясните ограничения", paragraphs: ["Документы, деньги, украшения и небольшие хрупкие предметы удобно заранее убрать в отдельное место. Это помогает избежать лишнего перемещения вещей и вопросов в процессе. Если какую-то комнату или полку трогать не нужно, скажите об этом в начале.", "Сообщите об особых покрытиях и пожеланиях по средствам. LumaClean может использовать свои средства или ваши; конкретные ограничения лучше обсудить до визита. Не рассчитывайте, что по внешнему виду поверхности можно безошибочно определить все требования производителя."], bullets: ["Укажите предметы и зоны, которые нельзя перемещать или открывать.", "Подготовьте инструкции по уходу за необычными поверхностями, если они есть.", "Сообщите о животных и согласуйте, где они будут во время уборки."]},
        {id: "access", title: "Проверьте доступ и связь", paragraphs: ["Отправьте точный адрес в Белграде, подъезд, этаж и инструкцию по домофону. Убедитесь, что вода и электричество доступны. Если не сможете встретить команду сами, заранее согласуйте передачу ключей и контакт человека, который откроет квартиру.", "Будьте на связи во время уборки. Если ваши планы изменились, сообщите об этом как можно раньше. Иногда достаточно одного сообщения, чтобы уточнить, можно ли открыть шкаф или куда убрать предмет со стола."]},
        {id: "priorities", title: "Назовите несколько главных задач", paragraphs: ["Перед началом коротко пройдите по квартире и покажите приоритеты: например, кухню, сантехнику и согласованные окна. Дополнительную работу, о которой вспомнили на месте, сначала обсудите с командой — её выполнение и стоимость нельзя считать автоматически включёнными.", "По завершении проверьте согласованные зоны вместе с командой и задайте вопросы, пока все на месте. Для следующего визита сохраните список предпочтений: он полезнее, чем каждый раз заново объяснять привычный порядок."], bullets: ["Накануне: подтвердите доступ, объём и дополнительные работы.", "Перед приходом: уберите личные вещи и освободите проходы.", "В начале: покажите приоритеты и ограничения.", "В конце: вместе проверьте выполненные задачи."]},
      ],
    },
    sr: {
      slug: "kako-se-pripremiti-za-dolazak-tima", title: "Kako se pripremiti za dolazak tima za čišćenje",
      description: "Kratak spisak pre dolaska LumaClean tima: slobodne površine, lične stvari, pristup stanu, posebna uputstva i dogovoreni prioriteti.",
      category: "Pre dolaska", imageAlt: "Ilustracija slobodne radne površine sa uredno odloženim sitnicama i presavijenom tkaninom",
      lead: "Ne morate da operete stan pre dolaska tima. Korisna priprema znači pristup površinama, jasne želje i mogućnost da posao počne bez traženja ključeva, utičnica ili mesta za lične stvari.",
      sections: [
        {id: "clear", title: "Oslobodite površine koje se čiste", paragraphs: ["Sklonite odeću, papire i sitne lične stvari sa poda i radnih površina. Nije potrebno savršeno srediti ormare: dovoljno je odložiti predmete koji smetaju na unapred izabrano mesto. Tako tim ne mora da odlučuje gde pripadaju vaše stvari.", "Ako je dogovoreno unutrašnje čišćenje ormara, ispraznite odabrane police. Za rernu i frižider unapred proverite pripremu i isplanirajte gde će sadržaj privremeno stajati. Nemojte pomerati težak nameštaj zbog uobičajenog dolaska; pristup iza njega dogovorite ranije."], tip: "Počnite od radne ploče, sudopere, poda i polica iz dogovorenog obima. Nema potrebe da prethodno perete površine koje tim treba da očisti."},
        {id: "personal", title: "Odložite lične predmete i objasnite ograničenja", paragraphs: ["Dokumenta, novac, nakit i male lomljive predmete stavite na posebno mesto. To smanjuje nepotrebno pomeranje i pitanja tokom rada. Ako sobu ili policu ne treba dirati, navedite to na početku.", "Pomenite posebne materijale i želje u vezi sa sredstvima. LumaClean može koristiti svoja ili vaša sredstva; ograničenja je najbolje dogovoriti pre dolaska. Nije uvek moguće samo po izgledu površine prepoznati sva uputstva proizvođača."], bullets: ["Pokažite šta ne treba pomerati ili otvarati.", "Pripremite postojeća uputstva za neobične površine.", "Pomenite ljubimce i dogovorite gde će biti tokom čišćenja."]},
        {id: "access", title: "Proverite pristup i kontakt", paragraphs: ["Pošaljite tačnu adresu u Beogradu, ulaz, sprat i uputstvo za interfon. Proverite da su voda i struja dostupne. Ako niste tu, unapred dogovorite predaju ključa i kontakt osobe koja otvara stan.", "Ostanite dostupni preko dogovorenog kanala tokom posete. Ako se plan promeni, javite čim možete. Kratko pitanje ne bi trebalo da zaustavi posao zato što osoba koja može da odgovori nije dostupna."]},
        {id: "priorities", title: "Izdvojite najvažnije zadatke", paragraphs: ["Na početku kratko prođite kroz stan i pokažite prioritete: na primer kuhinju, sanitarije i dogovorene prozore. Ako se setite dodatnog posla, prvo ga razmotrite sa timom. Ne podrazumeva se da su njegovo izvršenje i cena već uključeni.", "Po završetku zajedno pregledajte dogovorene zone i postavite pitanja dok je tim još tu. Sačuvajte svoja uputstva za naredni dolazak kako ne biste svaki put objašnjavali isti raspored."], bullets: ["Dan ranije: potvrdite pristup, obim i dodatke.", "Pre dolaska: sklonite lične stvari i oslobodite prolaze.", "Na početku: pokažite prioritete i ograničenja.", "Na kraju: zajedno proverite dogovorene zadatke."]},
      ],
    },
    en: {
      slug: "prepare-for-cleaners-arrival", title: "How to prepare for your cleaners' arrival",
      description: "A practical pre-visit checklist for LumaClean customers: clear surfaces, personal belongings, apartment access, special care instructions and priorities.",
      category: "Before the visit", imageAlt: "Conceptual illustration of a clear counter with neatly gathered small objects and folded fabric",
      lead: "You do not need to wash your home before the cleaners arrive. Useful preparation means accessible surfaces, clear requests and a way to start without searching for keys, sockets or somewhere to put personal belongings.",
      sections: [
        {id: "clear", title: "Clear the surfaces that will be cleaned", paragraphs: ["Gather clothes, papers and small personal items from floors and work surfaces. You do not have to organise every cupboard perfectly: put things that obstruct access in a place you choose. This avoids asking the team to decide where your belongings belong.", "Empty the relevant shelves if internal cupboard cleaning is agreed. Check preparation for the oven or fridge in advance and plan where their contents will go temporarily. Do not move heavy furniture for a routine visit; discuss access behind it beforehand."], tip: "Start with the worktop, sink, floor and shelves included in the booking. There is no need to wash the areas the team is coming to clean."},
        {id: "personal", title: "Put personal items aside and explain boundaries", paragraphs: ["Keep documents, money, jewellery and small fragile objects in a separate place. This reduces unnecessary handling and questions during the visit. If a room or shelf should be left alone, say so at the start.", "Mention special finishes and preferences about cleaning products. LumaClean can use its own products or yours; discuss specific restrictions before the visit. The appearance of a surface alone does not always reveal the manufacturer's care requirements."], bullets: ["Identify items or areas that should not be moved or opened.", "Have existing care instructions for unusual surfaces ready.", "Mention pets and agree where they will stay during cleaning."]},
        {id: "access", title: "Check access and stay reachable", paragraphs: ["Send the exact Belgrade address, entrance, floor and intercom instructions. Check that water and electricity are available. If you cannot meet the team, agree the key handover and the contact person who will open the apartment.", "Remain reachable through the agreed contact method during the visit. If your plans change, let the team know as early as possible. A quick question should not hold up the work because the person who can answer is unavailable."]},
        {id: "priorities", title: "Name a few main priorities", paragraphs: ["Briefly walk through the apartment at the start and point out priorities, such as the kitchen, bathroom fittings and agreed windows. Discuss any extra task you remember on the day before it is added. Its availability and price should not be assumed to be included.", "Review the agreed areas together afterwards and ask questions while the team is there. Keep a list of preferences for the next visit so you do not have to explain the same arrangements again."], bullets: ["The day before: confirm access, scope and extras.", "Before arrival: put personal belongings away and clear walkways.", "At the start: show priorities and boundaries.", "At the end: review the agreed tasks together."]},
      ],
    },
  },
};
