import type {Article} from "./types";

export const regularDeep: Article = {
  id: "regular-deep", status: "published", publishedAt: "2026-09-15", updatedAt: "2026-09-15",
  image: "/media/articles/regular-deep.webp", services: ["regular", "deep"],
  relatedIds: ["frequency","kitchen","bathroom"],
  translations: {
    ru: {
      slug: "podderzhivayushchaya-ili-generalnaya-uborka",
      title: "Поддерживающая или генеральная: какую уборку выбрать",
      description: "Как выбрать между поддерживающей и генеральной уборкой квартиры в Белграде: задачи, состояние кухни и ванной, дополнительные работы и подготовка заявки.",
      category: "Выбор уборки", imageAlt: "Иллюстрация кухонного уголка с открытым шкафом в светлых и бирюзовых тонах",
      lead: "Полы вы моете каждую неделю, а до кухонных фасадов давно не доходили руки. Нужна ли из-за этого генеральная уборка всей квартиры? Не всегда. Рассказываем, чем отличаются два формата и как выбрать подходящий.",
      sections: [
        {id: "regular", title: "Когда достаточно поддерживающей уборки", paragraphs: ["Этот формат помогает сохранять порядок в квартире, которой регулярно занимаются. Основное внимание — доступным поверхностям, полу, кухне и санузлу. Он подходит, когда обычные следы повседневной жизни ещё не превратились в отдельную сложную задачу.", "Осмотрите квартиру при дневном свете. Если на полках лёгкая пыль, на полу следы обуви, а кухня требует обычного протирания, поддерживающий формат может быть подходящим. Но само слово «регулярная» не означает, что внутренняя часть всей техники и мебели включена в заказ."], bullets: ["В квартире уже поддерживают порядок между визитами.", "Доступ к поверхностям свободен.", "Нет больших участков стойких загрязнений, требующих отдельного согласования."]},
        {id: "deep", title: "Когда стоит выбрать генеральную", paragraphs: ["Генеральная уборка уместна, если обычного прохода по поверхностям уже недостаточно: уборку давно откладывали, кухне и ванной нужно больше внимания или хочется тщательно привести квартиру в порядок перед новым режимом регулярных визитов.", "При выборе важна не только дата последней уборки. В квартире, где часто готовят и живут с животными, нагрузка может быть выше. Посмотрите на фасады кухни, сантехнику, углы и другие места, до которых обычно не доходят руки. Опишите конкретные задачи вместо общей оценки «очень грязно»."], tip: "Сделайте общий кадр кухни и ванной и несколько крупных планов сложных мест. По ним проще согласовать формат, чем по одной фотографии комнаты из дверного проёма."},
        {id: "extras", title: "Генеральная не означает «вообще всё»", paragraphs: ["У LumaClean окна, балкон, духовка, холодильник и шкафы внутри выбираются как дополнительные работы. Их нужно указать заранее, даже если вы заказываете генеральную уборку. Уборка после ремонта, устранение плесени и последствий затопления не относятся к доступным форматам.", "Не стоит выбирать более дорогой формат только ради одной духовки. Иногда поддерживающая уборка с нужной дополнительной работой точнее отвечает задаче. И наоборот: несколько дополнительных опций не заменят правильно выбранный основной формат, если всей квартире требуется более тщательная уборка."]},
        {id: "choose", title: "Как описать задачу при обращении", paragraphs: ["Сообщите площадь, район Белграда, когда квартиру убирали и что сейчас беспокоит больше всего. Добавьте пожелания по окнам, технике и внутренним поверхностям шкафов. Если планируется уборка перед въездом или после выезда, уточните это сразу: для переезда есть отдельная услуга.", "Не нужно самостоятельно ставить квартире точный «диагноз». Можно написать: «Живём постоянно, полы моем, но кухня требует внимания; хотим ещё вымыть духовку внутри». Такой запрос помогает обсудить реальный объём и согласовать стоимость до начала работы."], bullets: ["Выберите основной результат: поддержать порядок или тщательно убрать накопившиеся загрязнения.", "Перечислите дополнительные работы отдельно.", "Уточните спорные задачи по фотографиям.", "После первой уборки обсудите подходящий режим следующих визитов."]},
      ],
    },
    sr: {
      slug: "redovno-ili-generalno-ciscenje", title: "Redovno ili generalno čišćenje: šta je potrebno vašem stanu?",
      description: "Kako izabrati redovno ili generalno čišćenje stana u Beogradu, prepoznati obim posla i unapred dogovoriti dodatne usluge.",
      category: "Izbor usluge", imageAlt: "Ilustracija svetle kuhinje sa otvorenim ormarićem i tirkiznim detaljima",
      lead: "Dva stana iste površine mogu zahtevati sasvim različit posao. U jednom je dovoljno obrisati svežu prašinu, dok se u drugom masnoća u kuhinji skupljala mesecima. Izbor čišćenja zato počinje stanjem prostora i onim što želite da se uradi.",
      sections: [
        {id: "regular", title: "Kada je redovno čišćenje dovoljno", paragraphs: ["Redovno čišćenje služi održavanju stana o kojem se već vodi računa. Fokus je na dostupnim površinama, podovima, kuhinji i kupatilu. Odgovara uobičajenim tragovima svakodnevnog života, dok nisu prerasli u poseban zahtevniji posao.", "Pogledajte stan pri dnevnom svetlu. Malo prašine na policama i tragovi obuće na podu razlikuju se od naslaga kojima treba posvetiti više pažnje. Naziv usluge ipak ne znači da je čišćenje unutrašnjosti svih uređaja i ormara automatski uključeno."], bullets: ["Stan se održava između dolazaka.", "Površinama može lako da se priđe.", "Nema većih upornih naslaga koje treba posebno dogovoriti."]},
        {id: "deep", title: "Kada izabrati generalno čišćenje", paragraphs: ["Generalno čišćenje ima smisla kada uobičajeno održavanje više nije dovoljno. Možda je čišćenje dugo odlagano, kuhinji i kupatilu treba više pažnje ili želite temeljniji početak pre redovnih dolazaka.", "Nije presudno samo koliko je prošlo od poslednjeg čišćenja. Često kuvanje i kućni ljubimci takođe utiču na stanje prostora. Pogledajte kuhinjske frontove, sanitarije i uglove koje obično preskačete. Konkretan opis zadatka korisniji je od poruke da je stan «veoma prljav»."], tip: "Pošaljite fotografiju cele kuhinje i kupatila, pa nekoliko detalja zahtevnijih mesta. Tako je lakše dogovoriti obim nego na osnovu jedne fotografije sa vrata."},
        {id: "extras", title: "Generalno ne znači da je baš sve uključeno", paragraphs: ["Kod LumaClean-a prozori, balkon, unutrašnjost rerne, frižidera i ormara biraju se kao dodatni poslovi. Navedite ih unapred i uz generalno čišćenje. Čišćenje posle renoviranja, uklanjanje buđi i posledica poplave nisu dostupni formati.", "Skuplji format nije neophodan samo zbog jedne rerne. Ponekad redovno čišćenje sa odgovarajućim dodatkom bolje odgovara potrebi. Obrnuto, nekoliko dodataka ne zamenjuje pravi osnovni format kada celom stanu treba temeljnija pažnja."]},
        {id: "choose", title: "Šta napisati u upitu", paragraphs: ["Navedite površinu, deo Beograda, kada je stan čišćen i šta vam je najvažnije. Posebno dodajte prozore, uređaje i unutrašnje police. Ako je povod useljenje ili iseljenje, napišite i to: postoji poseban format za selidbu.", "Ne morate sami da procenite tačnu kategoriju. Poruka «Stan održavamo, ali kuhinji treba pažnja; želeli bismo i čišćenje rerne iznutra» daje jasnu osnovu za razgovor. Cena i obim dogovaraju se pre početka rada."], bullets: ["Odredite cilj: održavanje ili temeljnije uklanjanje nakupljene prljavštine.", "Dodatne poslove navedite zasebno.", "Nedoumice razjasnite fotografijama.", "Posle prvog čišćenja razmotrite ritam narednih dolazaka."]},
      ],
    },
    en: {
      slug: "regular-or-deep-cleaning", title: "Regular or deep cleaning: what does your apartment need?",
      description: "Choose regular or deep apartment cleaning in Belgrade by the condition of your home. Understand the scope, optional extras and what to include in your enquiry.",
      category: "Choosing a service", imageAlt: "Conceptual illustration of a pale kitchen corner with an open cabinet and turquoise accents",
      lead: "Two apartments of the same size can need very different work. One has fresh dust and footprints; another has a kitchen that has not had thorough attention for months. Choose the service by the condition of your home and the result you need.",
      sections: [
        {id: "regular", title: "When regular cleaning is enough", paragraphs: ["Regular cleaning maintains a home that is already looked after. It focuses on accessible surfaces, floors, the kitchen and bathroom. It suits everyday marks before they become a separate, more demanding task.", "Look around in daylight. Light dust on shelves and footprints are different from persistent build-up. Also remember that a recurring visit does not automatically include the insides of every appliance and cupboard."], bullets: ["The apartment is maintained between visits.", "Surfaces are accessible.", "There are no large areas of stubborn build-up needing a separate discussion."]},
        {id: "deep", title: "When to choose deep cleaning", paragraphs: ["Deep cleaning makes sense when routine attention is no longer enough. Cleaning may have been postponed, the kitchen and bathroom may need more work, or you may want a thorough reset before arranging regular visits.", "The time since the last clean is only one clue. Frequent cooking and pets also affect the work involved. Check kitchen fronts, bathroom fittings and corners you tend to skip. Specific observations are more useful than simply describing the home as very dirty."], tip: "Send a full view of the kitchen and bathroom plus close-ups of difficult areas. This makes the scope easier to agree than a single photograph taken from the doorway."},
        {id: "extras", title: "Deep cleaning does not mean every possible task", paragraphs: ["LumaClean lists windows, the balcony, and the insides of the oven, fridge and cupboards as additional tasks. Mention them in advance, including when booking deep cleaning. Post-renovation cleaning, mould removal and flood recovery are not available service formats.", "A more expensive base service is not necessary just because you want an oven cleaned. Regular cleaning with the relevant extra may suit your needs. Equally, a few extras cannot substitute for the right base service if the whole apartment needs more thorough attention."]},
        {id: "choose", title: "How to describe what you need", paragraphs: ["Include the floor area, Belgrade neighbourhood, when the apartment was last cleaned and your main priorities. List windows, appliances and internal shelves separately. If you are moving in or out, say so: there is a dedicated moving service.", "You do not have to identify the exact category yourself. A message such as «We keep up with the floors, but the kitchen needs attention, and we would like the oven cleaned inside» gives a useful starting point. The scope and price are agreed before work starts."], bullets: ["Choose the main goal: maintain the home or address accumulated dirt.", "List optional tasks separately.", "Use photographs to clarify uncertain areas.", "Discuss a suitable rhythm for future visits after the first clean."]},
      ],
    },
  },
};
