"use client";
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import type {ChannelSummary} from '@/lib/agent/channel-diagnostics';
export function CustomerChannels({channels}:{channels:ChannelSummary}){
 const router=useRouter(),[pending,start]=useTransition(),[message,setMessage]=useState('');
 async function command(payload:unknown){try{const response=await fetch('/api/admin/ai-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),value=await response.json();setMessage(response.ok?(value.result?.code??'Сохранено'):value.error??'Не удалось сохранить');router.refresh();}catch{setMessage('Соединение недоступно');}}
 return <section className="crm-section" id="customer-channels"><h2>Customer channels</h2><p>Один Inbox и AI. Каждый канал включается отдельно. Telegram для клиентов должен отличаться от бота уведомлений администратора.</p>{channels.map(c=><article key={c.channel}><h3>{c.channel} · {c.ready?'Соединение проверено':c.configured?'Нужна проверка соединения':'Не подключён'}</h3><p>Режим: {c.mode}. Диагностика: {c.diagnostic}. Последний webhook: {c.lastWebhook??'нет'}. Последняя отправка: {c.lastOutbound??'нет'} {c.deliveryStatus??''} {c.deliveryError??''}</p><p>Webhook: <code>{c.webhook}</code></p>{c.missing.length>0&&<p>Добавьте в серверные env Vercel: {c.missing.join(', ')}.</p>}{c.errors.length>0&&<p>{c.errors.join(', ')}</p>}{c.channel==='WHATSAPP'&&<p>Meta Business Portfolio → приложение WhatsApp → зарегистрированный номер и WABA → постоянный system-user token с разрешениями whatsapp_business_messaging/management → подписка webhook messages. Проверьте входящее сообщение. Свободный ответ доступен в течение 24 часов; шаблоны вне окна здесь не отправляются.</p>}{c.channel==='VIBER'&&<p>Нужно коммерческое одобрение чатбота Rakuten Viber и токен созданного бота. Подпишите webhook на message, delivered, seen, failed.</p>}{c.channel==='TELEGRAM'&&<p>Создайте отдельного клиентского бота через BotFather. Укажите webhook выше и secret_token из TELEGRAM_CUSTOMER_WEBHOOK_SECRET. Не меняйте webhook бота администратора.</p>}<button type="button" className="crm-button crm-button-secondary" disabled={pending||!c.configured} onClick={()=>start(()=>command({action:'channel-test',channel:c.channel}))}>Проверить соединение</button><form className="crm-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);start(()=>command({action:'channel-mode',channel:c.channel,mode:f.get('mode'),notifications:f.get('notifications')==='on',...(f.get('confirm')?{confirmAuto:true}:{})}));}}><label className="crm-field">Режим<select name="mode" defaultValue={c.mode} disabled={pending}><option>OFF</option><option disabled={!c.configured}>SHADOW</option><option disabled={!c.ready}>AUTO</option></select></label><label><input type="checkbox" name="confirm" disabled={!c.ready}/> Подтверждаю ограниченный AUTO этого канала</label><label><input type="checkbox" name="notifications" defaultChecked={c.notifications} disabled={!c.ready}/> Отправлять подтверждения и напоминания в этот канал</label><button className="crm-button" disabled={pending}>Сохранить канал</button></form></article>)}<p role="status">{message}</p></section>;
}
