"use client";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
export function InboxControls({id,control,identityVerified}:{id:string;control:string;identityVerified:boolean}){
  const router=useRouter(),[pending,startTransition]=useTransition(),[text,setText]=useState(""),[error,setError]=useState(""),[clientId,setClientId]=useState(""),[verified,setVerified]=useState(false);
  const replyAttempt=useRef<{text:string;id:string}|null>(null);
  async function command(payload:Record<string,unknown>){setError("");try{const r=await fetch("/api/admin/inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),b=await r.json();if(!r.ok){setError(b.error??"Не удалось выполнить действие");return;}if(payload.action==="reply"){setText("");replyAttempt.current=null;}router.refresh();}catch{setError("Связь временно недоступна");}}
  return <div className="inbox-controls"><div className="inbox-action-row">{control!=="HUMAN_CONTROL"&&control!=="CLOSED"?<button className="crm-button" disabled={pending} onClick={()=>startTransition(()=>command({action:"takeover",id}))}>Перехватить диалог</button>:<button className="crm-button" disabled={pending} onClick={()=>startTransition(()=>command({action:"resume",id}))}>Вернуть AI</button>}{control!=="CLOSED"&&<button className="crm-button secondary" disabled={pending} onClick={()=>startTransition(()=>command({action:"close",id}))}>Закрыть</button>}<button className="crm-button secondary" disabled={pending} onClick={()=>startTransition(()=>command({action:"retry",id}))}>Повторить обработку</button><button className="crm-button secondary" disabled={pending} onClick={()=>startTransition(()=>command({action:"read",id}))}>Прочитано</button><button className="crm-button secondary" onClick={()=>router.refresh()}>Обновить</button></div>{control==="HUMAN_CONTROL"&&<form onSubmit={e=>{e.preventDefault();startTransition(()=>command({action:"reply",id,requestId:(replyAttempt.current?.text===text?replyAttempt.current:(replyAttempt.current={text,id:crypto.randomUUID()})).id,text}));}}><label>Ответ клиенту<textarea aria-label="Ответ клиенту" maxLength={3000} rows={4} value={text} onChange={e=>setText(e.target.value)}/></label><button className="crm-button" disabled={pending||!text.trim()}>Отправить ответ</button></form>}{!identityVerified&&control==="HUMAN_CONTROL"&&<details><summary>Подтвердить существующего клиента</summary><p className="crm-hint">Используйте после независимой проверки клиента. Имя или названный телефон сами по себе не подтверждают личность.</p><label>ID клиента из CRM<input aria-label="ID клиента из CRM" value={clientId} maxLength={80} onChange={e=>setClientId(e.target.value)}/></label><label className="crm-checkbox"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Личность проверена по надёжному каналу</label><button className="crm-button secondary" disabled={pending||!clientId||!verified} onClick={()=>startTransition(()=>command({action:"verifyIdentity",id,clientId,verificationConfirmed:true}))}>Привязать клиента</button></details>}{error&&<p role="alert" className="crm-error">{error}</p>}</div>;
}
export function AgentModeControl({mode,enabled}:{mode:string;enabled:boolean}){
  const router=useRouter(),[value,setValue]=useState(mode),[confirm,setConfirm]=useState(false),[pending,startTransition]=useTransition(),[error,setError]=useState("");
  return <form className="inbox-mode" onSubmit={e=>{e.preventDefault();startTransition(async()=>{setError("");try{const r=await fetch("/api/admin/inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"mode",mode:value,...(confirm?{confirmAuto:true}:{})})});if(!r.ok){setError("Режим не изменён. Проверьте настройки и подтверждение AUTO.");return;}router.refresh();}catch{setError("Связь временно недоступна");}});}}><div><label htmlFor="ai-mode">AI-ответы включены</label><p className="crm-hint">{enabled?"Серверный переключатель включён":"Серверный AI_AGENT_ENABLED выключен"} · Текущий режим: {mode}</p></div><select id="ai-mode" value={value} onChange={e=>{setValue(e.target.value);setConfirm(false);}}><option value="OFF">OFF · только владелец</option><option value="SHADOW">SHADOW · предложения владельцу</option><option value="AUTO">AUTO · ответы и стандартная запись</option></select>{value==="AUTO"&&<label className="crm-checkbox"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Я проверил диалоги, правила длительности и маршруты; разрешаю AUTO</label>}<button className="crm-button secondary" disabled={pending||value==="AUTO"&&(!confirm||!enabled)}>Сохранить режим</button>{error&&<p role="alert">{error}</p>}</form>;
}
