'use client';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import type {LiveTestReport} from '@/lib/agent/live-test';
import {DayMap} from './routing-map';
const noPoints:Parameters<typeof DayMap>[0]['points']=[];
async function command(payload:unknown){const r=await fetch('/api/admin/ai-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error??'Не удалось выполнить действие');return b.result;}
export function StarterDuration({activeServices}:{activeServices:string[]}){
 const router=useRouter(),[pending,start]=useTransition(),[reserve,setReserve]=useState('10'),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState('');
 return <section className="crm-section" id="starter-duration"><h2>Подтвердить стартовые Duration Rules</h2><p>Ориентиры для обычного загрязнения и без extras. За пределами диапазона нужна ручная оценка.</p><ul><li>Regular: 1–100 м², 2 клинера, 150 минут.</li><li>Deep: 40–60 м², 2 клинера, 480 минут. Проверьте длину рабочего дня.</li></ul><label className="crm-field">Резерв уборки, минут<input type="number" value={reserve} onChange={e=>setReserve(e.target.value)} min={0} max={60} required/></label><p>Предложение: 10 минут сверх уборки. Можно изменить, включая 0. Значение действует после подтверждения. Транспортный буфер — отдельные 30 минут. Длительность extras остаётся NULL.</p><label className="crm-checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Я проверил площадь, команду, длительность и резерв и подтверждаю выбранное правило.</label><div className="inbox-action-row">{['regular','deep'].map(service=><button key={service} className="crm-button secondary" disabled={pending||!confirmed||activeServices.includes(service)||reserve.trim()===''||!Number.isInteger(Number(reserve))||Number(reserve)<0||Number(reserve)>60} onClick={()=>start(async()=>{try{await command({action:'starter-duration',service,reserveMinutes:Number(reserve),confirm:true});setMessage('Новая версия активирована, AuditLog сохранён.');setConfirmed(false);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Не удалось сохранить');}})}>{activeServices.includes(service)?`${service}: уже подтверждено`:`Подтвердить ${service}`}</button>)}</div><p>Изменить диапазон и extras можно в редакторе правил ниже.</p>{message&&<p role="status">{message}</p>}</section>;
}
export function BrowserMapsDiagnostic(){const [show,setShow]=useState(false);return <div><button type="button" className="crm-button secondary" onClick={()=>setShow(true)}>Проверить Maps JavaScript API</button>{show&&<><p>Настоящая карта для текущего домена. Ошибка доступа появится ниже. Places и TRANSIT проверяются отдельно.</p><DayMap points={noPoints}/></>}</div>;}
export function LiveBookingControl({preview,canRun,report:initial,previewUrl,today,testDate}:{today:string;testDate:string;preview:boolean;canRun:boolean;report:LiveTestReport|null;previewUrl:string|null}){
 const router=useRouter(),[pending,start]=useTransition(),[report,setReport]=useState(initial),[error,setError]=useState(''),[proof,setProof]=useState('');
 return <section className="crm-section" id="live-booking"><h2>Тест записи Website AI</h2><p>Синтетический клиент, реальные primary LLM, Places, TRANSIT, цена, длительность, слот и booking. Только Preview. Записи batch очищаются; общий SHADOW сохраняется.</p>{preview?<form onSubmit={e=>{e.preventDefault();const date=String(new FormData(e.currentTarget).get('date'));start(async()=>{setError('');try{setReport(await command({action:'live-test',date}));router.refresh();}catch(e){setError(e instanceof Error?e.message:'Тест недоступен');}});}}><label className="crm-field">Дата уборки<input name="date" type="date" defaultValue={testDate} min={today} required/></label><button className="crm-button" disabled={pending||!canRun}>{pending?'Проверяем путь записи…':'Запустить тест записи'}</button>{!canRun&&<p>Сначала устраните обязательные блокеры выше.</p>}</form>:<p>{previewUrl?<a className="crm-button secondary" href={previewUrl+'/admin/settings#live-booking'} target="_blank" rel="noopener noreferrer">Открыть тест в Preview</a>:'Preview ещё не подключён.'} На основном сайте тестовые Orders не создаются.</p>}{report&&<div role="status"><ul>{report.steps?.map(s=><li key={s.label}>{s.label} {s.ok?'✓':'✕'}</li>)}</ul><p><b>{report.status==='PASSED'&&report.cleaned?'Website AUTO технически готов':`Тест не пройден: ${report.blocker??'проверка продолжается'}`}</b></p><p>Очистка batch: {report.cleaned?'✓':'нужна проверка'}</p>{report.proof&&<details><summary>Отчёт для основного сайта</summary><p>Подпись, срок и конфигурация проверяются при переносе.</p><textarea aria-label="Отчёт Preview" readOnly rows={4} value={JSON.stringify(report.proof)}/></details>}</div>}<details><summary>Применить успешный отчёт Preview</summary><textarea aria-label="Подписанный отчёт" value={proof} onChange={e=>setProof(e.target.value)} maxLength={2000} rows={4}/><button className="crm-button secondary" disabled={pending||!proof.trim()} onClick={()=>start(async()=>{setError('');try{await command({action:'import-live-proof',proof});setProof('');router.refresh();}catch(e){setError(e instanceof Error?e.message:'Отчёт не принят');}})}>Проверить и применить отчёт</button></details>{error&&<p role="alert">{error}</p>}</section>;
}
