"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {MessageCircle,X,ArrowUp,Check} from "lucide-react";
import type {AgentLocale,BookingRecap} from "@/lib/agent/contracts";
import {siteContent} from "@/lib/content";
import {formatRsd} from "@/lib/pricing";
import "./website-chat.css";
type Chat={messages:{id:string;author:string;text:string;sentAt:string}[];control:string;pending:boolean;confirmation:{nonce:string;recap:BookingRecap}|null;booking:{reference:string;recap:BookingRecap}|null};
const copy={
ru:{open:"Написать LumaClean",title:"Давайте обсудим уборку",intro:"Опишите, какая уборка нужна. Ответим здесь — регистрация не требуется.",placeholder:"Ваше сообщение…",send:"Отправить",close:"Закрыть чат",language:"Язык диалога",wait:"Сообщение передано. Ожидаем ответа.",human:"На связи администратор",error:"Не удалось отправить. Повторите попытку.",rate:"Слишком много сообщений. Попробуйте через минуту.",confirm:"Подтвердить запись",confirmation:"Подтверждаю бронирование",booked:"Уборка подтверждена",recap:"Проверьте детали перед записью"},
"sr-Latn":{open:"Pišite LumaClean",title:"Razgovarajmo o čišćenju",intro:"Opišite čišćenje koje vam treba. Odgovorićemo ovde — bez registracije.",placeholder:"Vaša poruka…",send:"Pošalji",close:"Zatvori razgovor",language:"Jezik razgovora",wait:"Poruka je prosleđena. Čekamo odgovor.",human:"Administrator je na vezi",error:"Slanje nije uspelo. Pokušajte ponovo.",rate:"Previše poruka. Pokušajte za minut.",confirm:"Potvrdi rezervaciju",confirmation:"Potvrđujem",booked:"Čišćenje je potvrđeno",recap:"Proverite detalje pre rezervacije"},
"sr-Cyrl":{open:"Пишите LumaClean",title:"Разговарајмо о чишћењу",intro:"Опишите чишћење које вам треба. Одговорићемо овде — без регистрације.",placeholder:"Ваша порука…",send:"Пошаљи",close:"Затвори разговор",language:"Језик разговора",wait:"Порука је прослеђена. Чекамо одговор.",human:"Администратор је на вези",error:"Слање није успело. Покушајте поново.",rate:"Превише порука. Покушајте за минут.",confirm:"Потврди резервацију",confirmation:"Потврђујем",booked:"Чишћење је потврђено",recap:"Проверите детаље пре резервације"},
en:{open:"Message LumaClean",title:"Let's talk about your cleaning",intro:"Tell us what you need. We'll reply here — no registration needed.",placeholder:"Your message…",send:"Send",close:"Close chat",language:"Conversation language",wait:"Message received. Waiting for a reply.",human:"Our administrator is here",error:"Message wasn't sent. Please try again.",rate:"Too many messages. Please try again in a minute.",confirm:"Confirm booking",confirmation:"I confirm the booking",booked:"Cleaning confirmed",recap:"Check the details before booking"}};
function Recap({value,locale}:{value:BookingRecap;locale:AgentLocale}){
const lang=locale.startsWith("sr")?"sr":locale==="en"?"en":"ru",content=siteContent[lang];
return <dl className="website-chat-recap"><div><dt>{content.calculator.service}</dt><dd>{content.services.find(s=>s.id===value.service)?.name??value.service} · {value.area} m²</dd></div><div><dt>{new Intl.DateTimeFormat(locale==="sr-Cyrl"?"sr-RS":locale==="sr-Latn"?"sr-Latn-RS":locale,{timeZone:"Europe/Belgrade",weekday:"short",day:"numeric",month:"long"}).format(new Date(value.start))}</dt><dd>{new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Belgrade",hour:"2-digit",minute:"2-digit"}).format(new Date(value.start))} · Belgrade</dd></div><div><dt>{value.address}</dt><dd>{formatRsd(value.price,lang)}</dd></div>{value.extras.length>0&&<div><dt>{content.calculator.extras}</dt><dd>{value.extras.map(e=>`${content.calculator.labels[e.code]??e.code} × ${e.quantity}`).join(", ")}</dd></div>}</dl>;
}
export function WebsiteChat({locale:pageLocale}:{locale:string}){
const[open,setOpen]=useState(false),[locale,setLocale]=useState<AgentLocale>(pageLocale==="sr"?"sr-Latn":pageLocale==="en"?"en":"ru"),[chat,setChat]=useState<Chat|null>(null),[text,setText]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
const list=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),sendAttempt=useRef<{action:"message";id:string;text:string;locale:AgentLocale;confirmationNonce?:string}|null>(null),words=copy[locale];
const snapshotSequence=useRef(0);
useEffect(()=>{if(open)input.current?.focus();},[open]);
const refresh=useCallback(async()=>{const sequence=++snapshotSequence.current;const r=await fetch("/api/chat",{cache:"no-store",signal:AbortSignal.timeout(15000)}),body=await r.json();if(!r.ok)throw new Error();if(sequence===snapshotSequence.current)setChat(body.conversation);},[]);
useEffect(()=>{if(!open)return;let active=true;const tick=()=>{refresh().catch(()=>{if(active)setError(copy[locale].error);});};tick();const timer=setInterval(tick,5000);return()=>{active=false;clearInterval(timer);};},[open,locale,refresh]);
useEffect(()=>{if(open)list.current?.scrollTo({top:list.current.scrollHeight,behavior:"smooth"});},[open,chat?.messages.length]);
async function send(nonce?:string){
const message=nonce?words.confirmation:text.trim();if(!message||busy)return;setBusy(true);snapshotSequence.current++;setError("");
try{
if(!chat){const start=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"start",locale}),signal:AbortSignal.timeout(15000)});if(!start.ok)throw new Error();}
const previous=sendAttempt.current,payload=previous?.text===message&&previous.locale===locale&&previous.confirmationNonce===nonce?previous:{action:"message" as const,id:crypto.randomUUID(),text:message,locale,...(nonce?{confirmationNonce:nonce}:{})};sendAttempt.current=payload;
const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)}),body=await r.json();if(!r.ok){setError(r.status===429?words.rate:words.error);return;}snapshotSequence.current++;setChat(body.conversation);setText("");sendAttempt.current=null;input.current?.focus();
}catch{setError(words.error);}finally{setBusy(false);}}
return <div className="website-chat">{open&&<section className="website-chat-panel" role="dialog" aria-label={words.title} onKeyDown={e=>{if(e.key==="Escape")setOpen(false);}}><header><div><span>LumaClean / Belgrade</span><h2>{words.title}</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label={words.close}><X size={20}/></button></header><label className="website-chat-language"><span>{words.language}</span><select value={locale} onChange={e=>setLocale(e.target.value as AgentLocale)}><option value="ru">RU · Русский</option><option value="sr-Latn">SR · Latinica</option><option value="sr-Cyrl">SR · Ћирилица</option><option value="en">EN · English</option></select></label><div ref={list} className="website-chat-history" aria-live="polite" aria-relevant="additions text"><p className="website-chat-intro">{words.intro}</p>{chat?.messages.map(m=><article key={m.id} className={m.author==="CLIENT"?"website-chat-client":"website-chat-team"}><small>{m.author==="CLIENT"?locale==="en"?"You":locale==="ru"?"Вы":"Vi":"LumaClean"}</small><p>{m.text}</p><time dateTime={m.sentAt}>{new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit"}).format(new Date(m.sentAt))}</time></article>)}{chat?.confirmation&&<div className="website-chat-confirmation"><h3>{words.recap}</h3><Recap value={chat.confirmation.recap} locale={locale}/><button type="button" disabled={busy} onClick={()=>send(chat.confirmation!.nonce)}>{words.confirm}<Check size={16}/></button></div>}{chat?.booking&&<div className="website-chat-confirmation"><h3>{words.booked} <Check size={17}/></h3><small>{chat.booking.reference}</small><Recap value={chat.booking.recap} locale={locale}/></div>}</div><div className="website-chat-status" role="status">{error||(chat?.control==="HUMAN_CONTROL"?words.human:chat?.pending||chat?.messages.at(-1)?.author==="CLIENT"?words.wait:"")}</div><form onSubmit={e=>{e.preventDefault();void send();}}><textarea ref={input} aria-label={words.placeholder} placeholder={words.placeholder} maxLength={1500} rows={2} value={text} disabled={chat?.control==="CLOSED"} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}}/><button type="submit" disabled={busy||!text.trim()||chat?.control==="CLOSED"} aria-label={words.send}><ArrowUp size={19}/></button></form></section>}<button className="website-chat-launcher" type="button" aria-expanded={open} aria-label={words.open} onClick={()=>setOpen(v=>!v)}><MessageCircle size={21}/><span>{words.open}</span></button></div>;
}
