import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {normalizeTelegram,normalizeWhatsApp,normalizeViber,parseProviderJson,TelegramCustomerAdapter,WhatsAppCustomerAdapter,ViberCustomerAdapter,verifySignature,verifyWebhookSecret,channelConfiguration,verifyWhatsAppChallenge} from '../../src/lib/agent/channels';
import {safeMediaUrl,downloadChannelMedia,CHANNEL_FILE_MAX} from '../../src/lib/agent/channel-media';
import {mediaTicket,mediaTicketValid} from '../../src/lib/agent/channel-media-ticket';
import {channelReady,channelFingerprint} from '../../src/lib/agent/channel-diagnostics';
import {effectiveMode} from '../../src/lib/agent/readiness';
const message={update_id:1,message:{message_id:5,chat:{id:101,type:'private'},from:{id:101,is_bot:false,language_code:'ru'},text:'60 м², поддерживающая'}};
test('customer channel credentials and signatures do not reuse internal bot',()=>{
 process.env.TELEGRAM_BOT_TOKEN='test-admin';process.env.TELEGRAM_CUSTOMER_BOT_TOKEN='test-customer';process.env.TELEGRAM_CUSTOMER_WEBHOOK_SECRET='test-secret';
 assert(verifyWebhookSecret('test-secret'));assert(!verifyWebhookSecret('wrong'));process.env.TELEGRAM_CUSTOMER_BOT_TOKEN='test-admin';assert(!channelConfiguration('TELEGRAM').configured);assert(!verifyWebhookSecret('test-secret'));process.env.TELEGRAM_CUSTOMER_BOT_TOKEN='test-customer';
 process.env.WHATSAPP_APP_SECRET='test-meta';process.env.VIBER_CUSTOMER_BOT_TOKEN='test-viber';const body=Buffer.from('{"event":"message"}');
 for(const channel of ['WHATSAPP','VIBER'] as const){const hash=createHmac('sha256',channel==='WHATSAPP'?'test-meta':'test-viber').update(body).digest('hex'),signature=channel==='WHATSAPP'?`sha256=${hash}`:hash;assert(verifySignature(channel,body,signature));assert(!verifySignature(channel,Buffer.from('{}'),signature));assert(!verifySignature(channel,body,'bad'));}
});
test('Telegram normalization retains private identity, message id, quote and receipt',()=>{const event=normalizeTelegram({...message,message:{...message.message,date:123,reply_to_message:{message_id:3}}})!;assert.equal(event.externalMessageId,'101:5');assert.equal(event.externalUserId,'101');assert.equal(event.replyTo,'3');assert(event.receivedAt);assert.equal(event.providerSentAt?.getTime(),123000);assert.equal(normalizeTelegram({...message,message:{...message.message,chat:{id:-1,type:'group'}}}),null);});
test('Telegram photo picks largest file without retaining tokenized URLs',()=>{const event=normalizeTelegram({...message,message:{...message.message,text:undefined,photo:[{file_id:'small'},{file_id:'big',file_size:400}],caption:'Фото кухни'}})!;assert.equal(event.attachments?.[0].id,'big');assert.equal(event.attachments?.[0].kind,'image');assert.equal(event.text,'Фото кухни');assert(!JSON.stringify(event).includes('https:'));});
test('Telegram documents and unsupported input preserve an Inbox event',()=>{const event=normalizeTelegram({...message,message:{...message.message,text:undefined,document:{file_id:'pdf',mime_type:'application/pdf'}}})!;assert.equal(event.attachments?.[0].kind,'document');assert(normalizeTelegram({...message,message:{...message.message,text:undefined}}));});
test('WhatsApp normalizes only our WABA/phone and actual status callbacks',()=>{
 process.env.WHATSAPP_BUSINESS_ACCOUNT_ID='11111';process.env.WHATSAPP_PHONE_NUMBER_ID='22222';
 const raw={object:'whatsapp_business_account',entry:[{id:'11111',changes:[{field:'messages',value:{metadata:{phone_number_id:'22222'},messages:[{id:'wamid.test',from:'381601234567',timestamp:'1791111111',type:'image',image:{id:'99',mime_type:'image/jpeg'},context:{id:'quoted'}}],statuses:[{id:'out',recipient_id:'381601234567',status:'read',timestamp:'1791111112'}]}}]}]};
 const value=normalizeWhatsApp(raw);assert.equal(value.messages[0].verifiedPhone,'+381601234567');assert.equal(value.messages[0].replyTo,'quoted');assert.equal(value.statuses[0].status,'READ');raw.entry[0].id='foreign';assert.equal(normalizeWhatsApp(raw).messages.length,0);
});
test('Meta GET verification is exact and does not echo arbitrary challenge',()=>{process.env.WHATSAPP_VERIFY_TOKEN='test-verification';assert.equal(verifyWhatsAppChallenge(new URL('https://app.invalid?hub.mode=subscribe&hub.verify_token=test-verification&hub.challenge=123')),'123');assert.equal(verifyWhatsAppChallenge(new URL('https://app.invalid?hub.mode=subscribe&hub.verify_token=wrong&hub.challenge=123')),null);});
test('Viber preserves 64-bit IDs and maps seen to real READ only',()=>{const event=normalizeViber(parseProviderJson('{"event":"seen","timestamp":1791111111000,"message_token":5741311803571721087,"user_id":"test="}'));assert.equal(event.statuses[0].externalMessageId,'5741311803571721087');assert.equal(event.statuses[0].status,'READ');});
test('media downloader rejects arbitrary URLs, redirects and oversized input',async()=>{for(const url of ['http://127.0.0.1/x','https://user:pass@cdn.viber.com/x','https://cdn.viber.com:444/x','https://cdn.viber.com.evil.invalid/x','https://169.254.169.254/x'])assert.throws(()=>safeMediaUrl('VIBER',url));assert.throws(()=>safeMediaUrl('WHATSAPP','https://graph.facebook.com/x'));await assert.rejects(downloadChannelMedia('TELEGRAM',{kind:'image',id:'x',size:CHANNEL_FILE_MAX+1}),/ATTACHMENT_TOO_LARGE/);});
test('bounded Viber download validates PDF bytes and MIME before storage',async()=>{const mock=(async()=>new Response('%PDF-1.4\n%%EOF',{headers:{'content-type':'application/pdf'}})) as typeof fetch;assert.equal((await downloadChannelMedia('VIBER',{kind:'document',url:'https://cdn.viber.com/doc'},mock)).mime,'application/pdf');await assert.rejects(downloadChannelMedia('VIBER',{kind:'document',url:'https://cdn.viber.com/doc'},(async()=>new Response('evil',{headers:{'content-type':'application/pdf'}})) as typeof fetch),/INVALID_DOCUMENT/);});
test('short-lived outbound media ticket cannot access another file or expiry',()=>{process.env.VIBER_CUSTOMER_BOT_TOKEN='test-viber';const expires=Date.now()+120000,signature=mediaTicket('file-1',expires);assert(mediaTicketValid('file-1',String(expires),signature));assert(!mediaTicketValid('file-2',String(expires),signature));assert(!mediaTicketValid('file-1',String(Date.now()-1),signature));});
test('Telegram reports SENT, no simulated read receipt, and bounded rate-limit retry',async()=>{const adapter=new TelegramCustomerAdapter('test-customer',(async()=>Response.json({ok:true,result:{message_id:8}})) as typeof fetch);assert.deepEqual(await adapter.send({id:'test',externalThreadId:'101',text:'Hello'}),{status:'SENT',externalMessageId:'8'});const rate=new TelegramCustomerAdapter('test-customer',(async()=>Response.json({ok:false,parameters:{retry_after:70}},{status:429})) as typeof fetch);assert.equal((await rate.send({id:'t',externalThreadId:'101',text:'Hi'})).retryAfterSeconds,70);});
test('ambiguous provider outcome is terminal UNKNOWN rather than unsafe retry',async()=>{const adapter=new TelegramCustomerAdapter('test-customer',(async()=>{throw Error('private-token-must-not-escape');}) as typeof fetch),result=await adapter.send({id:'t',externalThreadId:'101',text:'Hi'});assert.equal(result.status,'UNKNOWN');assert(!result.retryable);assert(!JSON.stringify(result).includes('private-token'));});
test('WhatsApp rejects out-of-window free text without contacting provider',async()=>{for(const key of ['WHATSAPP_ACCESS_TOKEN','WHATSAPP_APP_SECRET','WHATSAPP_VERIFY_TOKEN'])process.env[key]='test-only';process.env.WHATSAPP_GRAPH_VERSION='v25.0';process.env.WHATSAPP_PHONE_NUMBER_ID='22222';process.env.WHATSAPP_BUSINESS_ACCOUNT_ID='11111';const adapter=new WhatsAppCustomerAdapter((async()=>{assert.fail('must not call');}) as typeof fetch);assert.equal((await adapter.send({id:'t',externalThreadId:'381601234567',text:'Hello',lastInboundAt:new Date(0)})).errorCode,'WHATSAPP_TEMPLATE_REQUIRED');});
test('WhatsApp native send retains message id and Viber permanent failures are visible',async()=>{const wa=new WhatsAppCustomerAdapter((async(_input,init)=>{assert.equal(JSON.parse(String(init?.body)).to,'+381601234567');return Response.json({messages:[{id:'wamid.out'}]});}) as typeof fetch);assert.equal((await wa.send({id:'t',externalThreadId:'381601234567',text:'Hello',lastInboundAt:new Date()})).externalMessageId,'wamid.out');const viber=new ViberCustomerAdapter((async()=>Response.json({status:6})) as typeof fetch);assert.equal((await viber.send({id:'t',externalThreadId:'user=',text:'Hi'})).errorCode,'VIBER_6');});
test('Website AUTO remains independent of OFF customer transports',()=>{process.env.AI_AGENT_ENABLED='true';const settings={aiAgentMode:'AUTO' as const,aiChannelModes:{WEBSITE:'AUTO',TELEGRAM:'OFF',WHATSAPP:'OFF',VIBER:'OFF'}};assert.equal(effectiveMode(settings,'WEBSITE'),'AUTO');for(const c of ['TELEGRAM','WHATSAPP','VIBER'] as const)assert.equal(effectiveMode(settings,c),'OFF');});

test('full provider text limits reach Inbox normalization instead of silent loss',()=>{assert.equal(normalizeTelegram({...message,message:{...message.message,text:'x'.repeat(4096)}})?.text.length,4096);assert.throws(()=>normalizeTelegram({...message,message:{...message.message,text:'x'.repeat(4097)}}),/INVALID_TELEGRAM_UPDATE/);});
test('media metadata over limit is a permanent visible rejection before download',async()=>{const request=(async()=>Response.json({url:'https://lookaside.fbsbx.com/file',mime_type:'image/jpeg',file_size:CHANNEL_FILE_MAX+1})) as typeof fetch;await assert.rejects(downloadChannelMedia('WHATSAPP',{kind:'image',id:'123'},request),/ATTACHMENT_TOO_LARGE/);});

test('WhatsApp image and PDF upload use official media IDs before durable send',async()=>{
 for(const mime of ['image/jpeg','application/pdf']){let calls=0;const adapter=new WhatsAppCustomerAdapter((async(input,init)=>{calls++;if(String(input).endsWith('/media')){assert(init?.body instanceof FormData);assert.equal(init.body.get('messaging_product'),'whatsapp');return Response.json({id:'98765'});}const value=JSON.parse(String(init?.body)),type=mime.startsWith('image/')?'image':'document';assert.equal(value[type].id,'98765');assert.equal(value[type].caption,'For you');assert.equal(value.to,'+381601234567');return Response.json({messages:[{id:'wamid.media'}]});}) as typeof fetch);assert.equal((await adapter.send({id:'media',externalThreadId:'381601234567',text:'For you',lastInboundAt:new Date(),attachment:{id:'file',bytes:Buffer.from('synthetic'),mime}})).status,'SENT');assert.equal(calls,2);}
});
test('Viber image uses expiring signed media link without leaking bot token',async()=>{process.env.VIBER_CUSTOMER_BOT_TOKEN='test-viber';const adapter=new ViberCustomerAdapter((async(_input,init)=>{const value=JSON.parse(String(init?.body));assert.equal(value.type,'picture');assert(!value.media.includes('test-viber'));assert(new URL(value.media).searchParams.get('expires'));return new Response('{"status":0,"message_token":5741311803571721087}',{headers:{'Content-Type':'application/json'}});}) as typeof fetch);const result=await adapter.send({id:'test',externalThreadId:'user=',text:'Photo',attachment:{id:'file',bytes:Buffer.from('synthetic'),mime:'image/jpeg'}});assert.equal(result.status,'SENT');assert.equal(result.externalMessageId,'5741311803571721087');});

test('credential-bound connection remains usable beyond a day but rejects rotated credentials',()=>{const previous=process.env.TELEGRAM_CUSTOMER_BOT_TOKEN;process.env.TELEGRAM_CUSTOMER_BOT_TOKEN='test-customer';process.env.TELEGRAM_CUSTOMER_WEBHOOK_SECRET='test-secret';const settings={customerChannelDiagnostics:{TELEGRAM:{ok:true,at:new Date(Date.now()-172800000).toISOString(),fingerprint:channelFingerprint('TELEGRAM')}}};assert(channelReady(settings,'TELEGRAM'));process.env.TELEGRAM_CUSTOMER_BOT_TOKEN='test-rotated';assert(!channelReady(settings,'TELEGRAM'));process.env.TELEGRAM_CUSTOMER_BOT_TOKEN=previous;});
