import test from 'node:test';
import assert from 'node:assert/strict';
import {estimateDuration,type DurationConfig} from '../../src/lib/domain/duration';
import {effectiveMode,cleanerReadiness} from '../../src/lib/agent/readiness';
import {explicitConfirmation} from '../../src/lib/agent/policy';
import {aiSettingsSchema} from '../../src/lib/agent/settings';
const rule:DurationConfig={id:'rule',serviceId:'regular',version:1,active:true,minArea:1,maxArea:100,cleanerCount:2,referenceArea:100,baseMinutes:150,minutesPerSquare:0,soilMultipliers:{NORMAL:1},extraMinutes:{oven:null,fridge:20},reserveMinutes:15,unknownExtraReserveMinutes:40};
const input={serviceId:'regular',area:50,soilLevel:'NORMAL',requiredCleaners:2,extras:[]};
test('configured duration preserves owner rule without an invented extrapolation',()=>{const r=estimateDuration(input,[rule])!;assert.equal(r.confidence,'CONFIGURED');assert.equal(r.estimatedDurationMinutes,150);assert.equal(r.cleaningReserveMinutes,15);assert.equal(estimateDuration({...input,area:101},[rule]),null);});
test('NULL extras retain partial estimate and reserve per unknown quantity',()=>{const r=estimateDuration({...input,extras:[{code:'oven',quantity:2},{code:'fridge',quantity:1}]},[rule])!;assert.equal(r.confidence,'PARTIALLY_CONFIGURED');assert.equal(r.estimatedDurationMinutes,170);assert.equal(r.cleaningReserveMinutes,95);assert.deepEqual(r.unknownExtras,['oven']);});
test('unknown extras without an explicit reserve forbid automatic scheduling',()=>assert.equal(estimateDuration({...input,extras:[{code:'oven',quantity:1}]},[{...rule,unknownExtraReserveMinutes:0}]),null));
test('oversized uncertainty reserve cannot silently fit into a normal slot',()=>assert.equal(estimateDuration({...input,extras:[{code:'oven',quantity:100}]},[rule]),null));
test('channel ceilings isolate Website AUTO from every other channel',()=>{process.env.AI_AGENT_ENABLED='true';const s={aiAgentMode:'AUTO' as const,aiChannelModes:{WEBSITE:'AUTO',TELEGRAM:'OFF',WHATSAPP:'OFF',VIBER:'OFF'}};assert.equal(effectiveMode(s,'WEBSITE'),'AUTO');for(const channel of ['TELEGRAM','WHATSAPP','VIBER'] as const)assert.equal(effectiveMode(s,channel),'OFF');assert.equal(effectiveMode({...s,aiAgentMode:'SHADOW'},'WEBSITE'),'SHADOW');assert.equal(effectiveMode({...s,aiAgentMode:'OFF'},'WEBSITE'),'OFF');process.env.AI_AGENT_ENABLED='false';assert.equal(effectiveMode(s,'WEBSITE'),'OFF');});
test('cleaner payout and languages are warnings, hours/location/active are mandatory',()=>{const c={active:true,name:'Verifier',phone:'+381601234567',homeCoordinatesConfirmed:true,homeAddress:'Synthetic',homeLatitude:44.8,homeLongitude:20.4,languages:[],payoutPercent:null,availability:[{kind:'WEEKLY',startMinute:480,endMinute:1080}]};assert(cleanerReadiness(c).ready);assert(!cleanerReadiness({...c,availability:[]}).ready);assert(!cleanerReadiness({...c,homeLatitude:null}).ready);assert(!cleanerReadiness({...c,active:false}).ready);});
test('only full explicit recap assent is accepted',()=>{for(const text of ['Да','подходит','записывайте','da, potvrđujem'])assert(explicitConfirmation(text));for(const text of ['Не подходит','подходит?','записывайте, если будет скидка','Да, но другой адрес'])assert(!explicitConfirmation(text));});
test('cost/scope settings cannot enable unsupported integrations or unbounded loops',()=>{const input={action:'settings',channels:{WEBSITE:'AUTO',TELEGRAM:'OFF',WHATSAPP:'OFF',VIBER:'OFF'},allowedServices:['regular'],canary:true,maxMessages:200,maxModelCalls:8,maxToolSteps:6,maxConversationCost:0.1,dailyWarning:5};assert(aiSettingsSchema.safeParse(input).success);assert(!aiSettingsSchema.safeParse({...input,maxToolSteps:999}).success);assert(!aiSettingsSchema.safeParse({...input,channels:{...input.channels,WHATSAPP:'AUTO'}}).success);assert(!aiSettingsSchema.safeParse({...input,canary:false}).success);});

test('owner Deep starter keeps 480 minutes, two cleaners and separate 30 minute reserve',()=>{const deep={...rule,serviceId:'deep',minArea:40,maxArea:60,referenceArea:50,baseMinutes:480,reserveMinutes:30};const result=estimateDuration({...input,serviceId:'deep'},[deep])!;assert.equal(result.confidence,'CONFIGURED');assert.equal(result.estimatedDurationMinutes,480);assert.equal(result.cleaningReserveMinutes,30);assert.equal(result.estimatedDurationMinutes+result.cleaningReserveMinutes,510);assert.equal(estimateDuration({...input,serviceId:'deep',area:61},[deep]),null);const regular=estimateDuration(input,[{...rule,reserveMinutes:30}])!;assert.equal(regular.estimatedDurationMinutes,150);assert.equal(regular.cleaningReserveMinutes,30);});
test('Preview service selector permits Deep and rejects unsupported services',()=>{assert(aiSettingsSchema.safeParse({action:'live-test',date:'2026-10-10',service:'deep'}).success);assert(!aiSettingsSchema.safeParse({action:'live-test',date:'2026-10-10',service:'office'}).success);});
